import type { LandingLocaleData } from './types'

export const deLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': 'SELBST GEHOSTET',
    'CODING-AGENT OPERATIONS': 'BETRIEB VON CODING-AGENTEN',
    'Work with AI agents ': 'Betreibe KI-Agenten ',
    'as a system': 'als ein System',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'ThreadCells koordiniert native CLI-Agenten, führt offene Workflows über Modell-Turns hinweg fort und pflegt die zugrunde liegende Orchestrierungsumgebung – auf deinem eigenen Linux-Host.',
    'View on GitHub': 'Auf GitHub ansehen',
    'Read the docs': 'Dokumentation lesen',
    'Start the work. Watch the system. Step in only when it needs you.': 'Starte die Arbeit. Beobachte das System. Greife nur ein, wenn es dich braucht.',
    'CONTROL / RESULT': 'STEUERUNG / ERGEBNIS',
    'ThreadCells operating principles': 'Betriebsprinzipien von ThreadCells',
    'THE HARD PART': 'DIE EIGENTLICHE HERAUSFORDERUNG',
    'Starting more agents is easy.': 'Mehr Agenten zu starten ist einfach.',
    'Knowing what is true is not.': 'Den tatsächlichen Zustand zu kennen nicht.',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': 'Welcher Prozess besitzt den Worktree? Welche Sitzung ist nur untätig und welche beendet? Fehlt der Maschine Provider-Kapazität, ein Arbeitskontext oder Kapazität für rechenintensive Ausführung? Hat der Reviewer ein Ergebnis geliefert oder nur aufgehört, Ausgabe zu erzeugen?',
    'Operational questions ThreadCells answers': 'Betriebsfragen, die ThreadCells beantwortet',
    'SUPERVISOR': 'SUPERVISOR',
    'RUNNING': 'LÄUFT',
    'provider 01 / 03': 'Provider 01 / 03',
    'WORKER': 'WORKER',
    'COMPLETE': 'ABGESCHLOSSEN',
    'result persisted': 'Ergebnis gespeichert',
    'REVIEWER': 'REVIEWER',
    'READY': 'BEREIT',
    'context 02 / 02': 'Kontext 02 / 02',
    'OWNER GATE': 'OWNER-ENTSCHEIDUNG',
    'AUTHORITY': 'BERECHTIGUNG',
    'GATED': 'WARTET',
    'decision required': 'Entscheidung erforderlich',
    'THE CONTROL PLANE': 'DIE STEUERUNGSEBENE',
    'One place to see the work,': 'Arbeit, Host und Übergabe',
    'the host, and the handoff.': 'an einem Ort.',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'ThreadCells bündelt native Agentenausführung in einer Betriebsoberfläche: Sitzungen, Projekte, Terminals, Profile, Kapazitäten, Workflows, Dokumentation, optionale installationsweite Telegram-Lebenszyklusmeldungen und die Identität des aktuellen Builds.',
    'ThreadCells Home showing 21 real sessions, 166 agents, aggregate lifecycle counts, and dense session status summaries': 'ThreadCells-Startseite mit 21 realen Sitzungen, 166 Agenten, zusammengefassten Lebenszykluszahlen und kompakten Sitzungsstatusübersichten',
    'HOME / EXECUTION OVERVIEW': 'START / AUSFÜHRUNGSÜBERSICHT',
    'Real release system · sensitive material excluded': 'Reales Release-System · sensible Inhalte ausgeschlossen',
    'LIVE RELEASE SYSTEM': 'AKTIVES RELEASE-SYSTEM',
    'LIVE RELEASE SYSTEM · IDENTITIES ANONYMIZED': 'AKTIVES RELEASE-SYSTEM · IDENTITÄTEN ANONYMISIERT',
    'Session truth': 'Tatsächlicher Sitzungsstatus',
    'Provider, profile, lifecycle, project, and active work remain visible.': 'Provider, Profil, Lebenszyklus, Projekt und aktive Arbeit bleiben sichtbar.',
    'Operational scale': 'Betrieb im großen Maßstab',
    'First, Last, and Total summaries keep large durable histories readable.': 'Erste-, Letzte- und Gesamtübersichten halten auch umfangreiche dauerhafte Verläufe lesbar.',
    'CORE IDEAS': 'KERNGEDANKEN',
    'A control room built around': 'Ein Kontrollraum für',
    'the failure modes that matter.': 'die entscheidenden Fehlerfälle.',
    'WORKFLOW': 'WORKFLOW',
    'Intent goes out.': 'Der Auftrag geht hinaus.',
    'Evidence comes back.': 'Der Nachweis kommt zurück.',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': 'Der Coding-Agent bleibt nativ. ThreadCells macht den umgebenden Lebenszyklus transparent.',
    'LIVE RELEASE TOUR': 'TOUR DURCH DAS REALE SYSTEM',
    'See the control plane in motion.': 'Erlebe die Steuerungsebene im Betrieb.',
    'A tour of the real release system: Home, multi-agent work, Agents, provider-reported Statistics, Housekeeping, capacity, and redacted notification settings. Operational values and lifecycle states are real; Session and Project labels are anonymized.': 'Eine Tour durch das reale Release-System: Startseite, Multi-Agenten-Arbeit, Agents, vom Provider gemeldete Statistiken, Housekeeping, Kapazität und geschwärzte Benachrichtigungseinstellungen. Betriebswerte und Lebenszykluszustände sind real; Sitzungs- und Projektnamen sind anonymisiert.',
    'THREADCELLS / LIVE DATA · IDENTITIES ANONYMIZED': 'THREADCELLS / ECHTE DATEN · IDENTITÄTEN ANONYMISIERT',
    'Live ThreadCells release-system tour': 'Tour durch das aktive ThreadCells-Release-System',
    'The demo video is unavailable in this browser.': 'Das Demovideo ist in diesem Browser nicht verfügbar.',
    'PRODUCT EXPERIENCE': 'PRODUKTERLEBNIS',
    'The workflow and the host,': 'Workflow und Host',
    'in one operating view.': 'in einer Betriebsansicht.',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': 'Öffne die reale Sitzung hinter der Übersicht, halte die Laufzeitumgebung gesund und leite nur wichtige Entscheidungen an den Owner weiter, ohne dauerhaften Kontext zu verlieren.',
    'Expanded live ThreadCells session with processing and recovery-replaced agents': 'Erweiterte Live-ThreadCells-Sitzung mit einem aktiven und einem bei der Wiederherstellung ersetzten Agenten',
    'SESSION / MULTI-AGENT WORKFLOW': 'SITZUNG / MULTI-AGENTEN-WORKFLOW',
    'Real lifecycle state and durable recovery evidence': 'Reale Lebenszykluszustände und dauerhafte Wiederherstellungsnachweise',
    'ThreadCells Agents showing mixed lifecycle states and a stable action row': 'ThreadCells Agents mit gemischten Lebenszykluszuständen und einer stabilen Aktionsleiste',
    'AGENTS / LIFECYCLE CONTROL': 'AGENTEN / LEBENSZYKLUSSTEUERUNG',
    'Status, profile, workflow, and actions stay aligned': 'Status, Profil, Workflow und Aktionen bleiben ausgerichtet',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'ThreadCells Housekeeping mit Datenträgerzustand, geschützten Backups, Zeitplan und Bereinigungsrichtlinie',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / SERVERPFLEGE',
    'Plan, revalidate, protect active work': 'Planen, erneut prüfen, aktive Arbeit schützen',
    'ThreadCells Orchestration Capacity showing independent execution limits and host pressure': 'ThreadCells-Orchestrierungskapazität mit unabhängigen Ausführungslimits und Hostauslastung',
    'CAPACITY / HOST ADMISSION': 'KAPAZITÄT / HOST-ZULASSUNG',
    'Resident, provider, work, and heavy limits stay independent': 'Limits für Resident, Provider, Work und Heavy bleiben unabhängig',
    'ThreadCells Statistics showing provider-reported token usage by session and profile': 'ThreadCells-Statistik mit vom Provider gemeldeter Token-Nutzung nach Sitzung und Profil',
    'STATISTICS / PROVIDER TELEMETRY': 'STATISTIK / PROVIDER-TELEMETRIE',
    'Reported values stay separate from unknown data': 'Gemeldete Werte bleiben von unbekannten Daten getrennt',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': 'ThreadCells-Einstellungen für Telegram-Benachrichtigungen mit sichtbar geschwärzten Ziel- und Anmeldedatenfeldern',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / OWNER-AUFMERKSAMKEIT',
    'One low-noise installation-global route': 'Ein ruhiger Benachrichtigungskanal für die gesamte Installation',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': 'AKTIVES SYSTEM · SENSIBLE FELDER GESCHWÄRZT',
    'project authority resolved': 'Projektberechtigung geklärt',
    'provider capacity admitted': 'Provider-Kapazität zugelassen',
    'session cao-atlas-control started': 'Sitzung cao-atlas-control gestartet',
    'resident': 'resident',
    'provider': 'Provider',
    'work context': 'Arbeitskontext',
    'heavy': 'rechenintensiv',
    'NATIVE BY DESIGN': 'BEWUSST NATIV',
    'Keep the coding agent.': 'Behalte deinen Coding-Agenten.',
    'Add the operating system around it.': 'Ergänze das Betriebssystem darum.',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'ThreadCells steuert native Provider-CLIs in realen tmux-Terminals. Provider-Adapter melden, was der installierte Host tatsächlich unterstützt; nicht unterstützte Funktionen bleiben sichtbar, anstatt simuliert zu werden.',
    'Codex reference adapter and first-class Claude Code adapter': 'Codex-Referenzadapter und vollwertiger Claude-Code-Adapter',
    'Provider-native authentication remains with the operator': 'Provider-native Authentifizierung bleibt beim Betreiber',
    'Profiles and provider configuration are versioned control-plane artifacts': 'Profile und Provider-Konfiguration sind versionierte Artefakte der Steuerungsebene',
    'TECHNICAL PREVIEW': 'TECHNISCHE VORSCHAU',
    'A practical first run.': 'Ein praxisnaher Einstieg.',
    'Honest alpha boundaries.': 'Ehrliche Grenzen der Alpha-Version.',
    'ThreadCells is for individual developers and trusted small teams that operate several coding agents on one Linux host and want durable workflow state instead of a pile of terminal tabs.': 'ThreadCells richtet sich an einzelne Entwickler und kleine, vertrauenswürdige Teams, die mehrere Coding-Agenten auf einem Linux-Host betreiben und einen dauerhaften Workflow-Status statt eines Stapels Terminal-Tabs wünschen.',
    'Start on a trusted Linux host': 'Auf einem vertrauenswürdigen Linux-Host starten',
    'The supported baseline is Ubuntu or Debian with Python 3, Git, tmux, Node.js/npm for the Web build, and at least one provider CLI you have authenticated.': 'Die unterstützte Basis ist Ubuntu oder Debian mit Python 3, Git, tmux, Node.js/npm für den Web-Build und mindestens einer authentifizierten Provider-CLI.',
    'Open the installation guide': 'Installationsanleitung öffnen',
    'Provider support stays explicit': 'Provider-Unterstützung bleibt transparent',
    'Eight built-in adapters normalize launch and lifecycle. Codex is the release-acceptance reference; readiness, resume, usage, and model controls still depend on the installed provider CLI.': 'Acht integrierte Adapter vereinheitlichen Start und Lebenszyklus. Codex ist die Referenz für Release-Abnahmen; Bereitschaft, Wiederaufnahme, Nutzung und Modellsteuerung hängen weiterhin von der installierten Provider-CLI ab.',
    'Check provider compatibility': 'Provider-Kompatibilität prüfen',
    'Know where trust stops': 'Die Grenzen des Vertrauens kennen',
    'This alpha targets one trusted operator and one host. It is loopback-first, supports remote use through an SSH tunnel, and does not treat worktrees as security sandboxes or isolate hostile tenants.': 'Diese Alpha-Version ist für einen vertrauenswürdigen Betreiber und einen Host ausgelegt. Sie bindet standardmäßig an loopback, unterstützt Fernzugriff per SSH-Tunnel und behandelt Worktrees weder als Sicherheitssandboxes noch als Isolation für nicht vertrauenswürdige Mandanten.',
    'Read the alpha limitations': 'Alpha-Einschränkungen lesen',
    'MACHINE OWNERSHIP': 'HOHEIT ÜBER DIE MASCHINE',
    'Your host.': 'Dein Host.',
    'Your terminals.': 'Deine Terminals.',
    'Your control.': 'Deine Kontrolle.',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'ThreadCells ist selbst gehostet und priorisiert Loopback. Es koordiniert leistungsfähige lokale Werkzeuge, stellt einen Worktree aber nicht als Sicherheitssandbox dar und verspricht keine Mandantentrennung zwischen nicht vertrauenswürdigen Nutzern.',
    'Loopback first': 'Loopback zuerst',
    'SSH-tunnel access is the supported preview boundary.': 'Der unterstützte Zugriffsweg der Vorschau ist ein SSH-Tunnel.',
    'Real terminals': 'Reale Terminals',
    'Inspectable tmux sessions, not hidden disposable jobs.': 'Nachvollziehbare tmux-Sitzungen statt versteckter Wegwerf-Jobs.',
    'OPEN SOURCE': 'OPEN SOURCE',
    'Inspect the control plane you trust with the machine.': 'Prüfe die Steuerungsebene, der du deine Maschine anvertraust.',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'ThreadCells steht unter der Apache License 2.0; die Herkunftsangaben zum Upstream bleiben in den entsprechenden Rechts- und Herkunftsdokumenten erhalten.',
    'Stop guessing what the agents are doing.': 'Rätsel nicht länger, was die Agenten tun.',
    'Run the work. See the machine. Keep the result.': 'Führe die Arbeit aus. Sieh den Zustand der Maschine. Bewahre das Ergebnis.',
    'Open Quick Setup': 'Quick Setup öffnen',
  },
  signals: ['KOORDINIERTE WORKFLOWS', 'GESCHÜTZTES HOUSEKEEPING', 'DAUERHAFTER VERLAUF', 'LOOPBACK ZUERST'],
  capabilities: [
    { title: 'Tatsächlicher Betriebszustand', copy: 'Sieh, was resident, aktiv, wartend, im Abbau, blockiert oder wirklich abgeschlossen ist, ohne den Zustand aus einem Terminal-Tab abzuleiten.' },
    { title: 'Worktree-Berechtigung', copy: 'Binde Arbeit an vertrauenswürdige Projekte und verwaltete Git-Worktrees. Schreibberechtigungen machen gleichzeitige Änderungen ausdrücklich sichtbar.' },
    { title: 'Dauerhafte Ergebnisse', copy: 'Delegierte Arbeit liefert ein gespeichertes Ergebnis, das ohne Verlust des Verlaufs zugestellt, bestätigt, angenommen und aus der aktiven Umgebung entfernt werden kann.' },
    { title: 'Eine gesunde Agentenumgebung', copy: 'ThreadCells überwacht den Hostdruck und entfernt geeignete Laufzeit-, Protokoll-, Cache-, Build- und Release-Reste sicher, während aktive Arbeit und dauerhafter Verlauf geschützt bleiben.' },
  ],
  steps: [
    { title: 'Sitzung erstellen', copy: 'Wähle ein vertrauenswürdiges lokales Projekt und ein Agenten- oder Supervisor-Profil.' },
    { title: 'Aufgabe übergeben', copy: 'Ein Supervisor kann zusammenhängende Arbeit an native CLI-Worker und Reviewer delegieren.' },
    { title: 'System beobachten', copy: 'ThreadCells führt den Workflow über Modell-Turns hinweg fort, während Sitzungen, Worktrees, Kapazitäten und Hostdruck sichtbar bleiben.' },
    { title: 'Bei Bedarf eingreifen', copy: 'Ergebnisse bleiben dauerhaft erhalten. Eine Owner-Entscheidung hält den Workflow nur an, wenn du wirklich gebraucht wirst.' },
  ],
  jsonLdFeatures: [
    'Persistente Sitzungen nativer CLI-Agenten',
    'Verwaltete Git-Worktrees und Schreibberechtigungen',
    'Dauerhafte Ergebnisse delegierter Arbeit',
    'Expliziter Workflow-Lebenszyklus und Owner-Entscheidungen',
    'Unabhängige Steuerung der Ausführungskapazitäten',
    'Housekeeping unter Beachtung der geschützten Menge und Entfernung geschlossener Laufzeiten',
    'Optionale installationsweite Telegram-Benachrichtigungen zum Lebenszyklus',
  ],
}
