import type { LandingLocaleData } from './types'

export const deLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': 'SELBST GEHOSTET',
    'CODING-AGENT OPERATIONS': 'BETRIEB VON CODING-AGENTEN',
    'Work with AI agents ': 'Betreibe KI-Agenten ',
    'as a system': 'als ein System',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'ThreadCells koordiniert native CLI-Agenten, führt offene Workflows über Modell-Turns hinweg fort und pflegt die zugrunde liegende Orchestrierungsumgebung – auf deinem eigenen Linux-Host.',
    'View on GitHub': 'Auf GitHub ansehen',
    'Read the docs': 'Dokumentation lesen',
    'Start the work. Watch the system. Step in only when it needs you.': 'Starte die Arbeit. Beobachte das System. Greife nur ein, wenn es dich braucht.',
    'CONTROL / RESULT': 'STEUERUNG / ERGEBNIS',
    'ThreadCells operating principles': 'Betriebsprinzipien von ThreadCells',
    'THE HARD PART': 'DIE EIGENTLICHE HERAUSFORDERUNG',
    'Starting more agents is easy.': 'Mehr Agenten zu starten ist einfach.',
    'Knowing what is true is not.': 'Den tatsächlichen Zustand zu kennen nicht.',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': 'Welcher Prozess besitzt den Worktree? Welche Sitzung ist nur untätig und welche beendet? Fehlt der Maschine Provider-Kapazität, ein Arbeitskontext oder Kapazität für rechenintensive Ausführung? Hat der Reviewer ein Ergebnis geliefert oder nur aufgehört, Ausgabe zu erzeugen?',
    'Operational questions ThreadCells answers': 'Betriebsfragen, die ThreadCells beantwortet',
    'SUPERVISOR': 'SUPERVISOR',
    'RUNNING': 'LÄUFT',
    'provider 01 / 03': 'Provider 01 / 03',
    'WORKER': 'WORKER',
    'COMPLETE': 'ABGESCHLOSSEN',
    'result persisted': 'Ergebnis gespeichert',
    'REVIEWER': 'REVIEWER',
    'READY': 'BEREIT',
    'context 02 / 02': 'Kontext 02 / 02',
    'OWNER GATE': 'OWNER-ENTSCHEIDUNG',
    'AUTHORITY': 'BERECHTIGUNG',
    'GATED': 'WARTET',
    'decision required': 'Entscheidung erforderlich',
    'THE CONTROL PLANE': 'DIE STEUERUNGSEBENE',
    'One place to see the work,': 'Arbeit, Host und Übergabe',
    'the host, and the handoff.': 'an einem Ort.',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'ThreadCells bündelt native Agentenausführung in einer Betriebsoberfläche: Sitzungen, Projekte, Terminals, Profile, Kapazitäten, Workflows, Dokumentation, optionale installationsweite Telegram-Lebenszyklusmeldungen und die Identität des aktuellen Builds.',
    'ThreadCells Home showing 21 real sessions, 166 agents, aggregate lifecycle counts, and dense session status summaries': 'ThreadCells-Startseite mit 21 realen Sitzungen, 166 Agenten, zusammengefassten Lebenszykluszahlen und kompakten Sitzungsstatusübersichten',
    'HOME / EXECUTION OVERVIEW': 'START / AUSFÜHRUNGSÜBERSICHT',
    'Real release system · sensitive material excluded': 'Reales Release-System · sensible Inhalte ausgeschlossen',
    'LIVE RELEASE SYSTEM': 'AKTIVES RELEASE-SYSTEM',
    'Session truth': 'Tatsächlicher Sitzungsstatus',
    'Provider, profile, lifecycle, project, and active work remain visible.': 'Provider, Profil, Lebenszyklus, Projekt und aktive Arbeit bleiben sichtbar.',
    'Operational scale': 'Betrieb im großen Maßstab',
    'First, Last, and Total summaries keep large durable histories readable.': 'Erste-, Letzte- und Gesamtübersichten halten auch umfangreiche dauerhafte Verläufe lesbar.',
    'CORE IDEAS': 'KERNGEDANKEN',
    'A control room built around': 'Ein Kontrollraum für',
    'the failure modes that matter.': 'die entscheidenden Fehlerfälle.',
    'WORKFLOW': 'WORKFLOW',
    'Intent goes out.': 'Der Auftrag geht hinaus.',
    'Evidence comes back.': 'Der Nachweis kommt zurück.',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': 'Der Coding-Agent bleibt nativ. ThreadCells macht den umgebenden Lebenszyklus transparent.',
    'LIVE RELEASE TOUR': 'TOUR DURCH DAS REALE SYSTEM',
    'See the control plane in motion.': 'Erlebe die Steuerungsebene im Betrieb.',
    'A short tour through the real release system: dense Home state, an expanded multi-agent session, protected Housekeeping, and independent capacity.': 'Eine kurze Tour durch das reale Release-System: eine informationsreiche Startseite, eine geöffnete Multi-Agenten-Sitzung, geschütztes Housekeeping und unabhängige Kapazitäten.',
    'THREADCELLS / LIVE RELEASE SYSTEM': 'THREADCELLS / AKTIVES RELEASE-SYSTEM',
    'Live ThreadCells release-system tour': 'Tour durch das aktive ThreadCells-Release-System',
    'The demo video is unavailable in this browser.': 'Das Demovideo ist in diesem Browser nicht verfügbar.',
    'PRODUCT EXPERIENCE': 'PRODUKTERLEBNIS',
    'The workflow and the host,': 'Workflow und Host',
    'in one operating view.': 'in einer Betriebsansicht.',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': 'Öffne die reale Sitzung hinter der Übersicht, halte die Laufzeitumgebung gesund und leite nur wichtige Entscheidungen an den Owner weiter, ohne dauerhaften Kontext zu verlieren.',
    'Expanded live ThreadCells session with one active owner and two completed reviewers': 'Geöffnete aktive ThreadCells-Sitzung mit einem aktiven Owner und zwei Reviewern, die ihre Arbeit abgeschlossen haben',
    'SESSION / MULTI-AGENT WORKFLOW': 'SITZUNG / MULTI-AGENTEN-WORKFLOW',
    'Real profiles, lifecycle, and durable completion': 'Reale Profile, Lebenszyklus und dauerhafter Abschluss',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'ThreadCells Housekeeping mit Datenträgerzustand, geschützten Backups, Zeitplan und Bereinigungsrichtlinie',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / SERVERPFLEGE',
    'Plan, revalidate, protect active work': 'Planen, erneut prüfen, aktive Arbeit schützen',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': 'ThreadCells-Einstellungen für Telegram-Benachrichtigungen mit sichtbar geschwärzten Ziel- und Anmeldedatenfeldern',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / OWNER-AUFMERKSAMKEIT',
    'One low-noise installation-global route': 'Ein ruhiger Benachrichtigungskanal für die gesamte Installation',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': 'AKTIVES SYSTEM · SENSIBLE FELDER GESCHWÄRZT',
    'project authority resolved': 'Projektberechtigung geklärt',
    'provider capacity admitted': 'Provider-Kapazität zugelassen',
    'session cao-atlas-control started': 'Sitzung cao-atlas-control gestartet',
    'resident': 'resident',
    'provider': 'Provider',
    'work context': 'Arbeitskontext',
    'heavy': 'rechenintensiv',
    'NATIVE BY DESIGN': 'BEWUSST NATIV',
    'Keep the coding agent.': 'Behalte deinen Coding-Agenten.',
    'Add the operating system around it.': 'Ergänze das Betriebssystem darum.',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'ThreadCells steuert native Provider-CLIs in realen tmux-Terminals. Provider-Adapter melden, was der installierte Host tatsächlich unterstützt; nicht unterstützte Funktionen bleiben sichtbar, anstatt simuliert zu werden.',
    'Codex reference adapter and first-class Claude Code adapter': 'Codex-Referenzadapter und vollwertiger Claude-Code-Adapter',
    'Provider-native authentication remains with the operator': 'Provider-native Authentifizierung bleibt beim Betreiber',
    'Profiles and provider configuration are versioned control-plane artifacts': 'Profile und Provider-Konfiguration sind versionierte Artefakte der Steuerungsebene',
    'MACHINE OWNERSHIP': 'HOHEIT ÜBER DIE MASCHINE',
    'Your host.': 'Dein Host.',
    'Your terminals.': 'Deine Terminals.',
    'Your control.': 'Deine Kontrolle.',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'ThreadCells ist selbst gehostet und priorisiert Loopback. Es koordiniert leistungsfähige lokale Werkzeuge, stellt einen Worktree aber nicht als Sicherheitssandbox dar und verspricht keine Mandantentrennung zwischen nicht vertrauenswürdigen Nutzern.',
    'Loopback first': 'Loopback zuerst',
    'SSH-tunnel access is the supported preview boundary.': 'Der unterstützte Zugriffsweg der Vorschau ist ein SSH-Tunnel.',
    'Real terminals': 'Reale Terminals',
    'Inspectable tmux sessions, not hidden disposable jobs.': 'Nachvollziehbare tmux-Sitzungen statt versteckter Wegwerf-Jobs.',
    'OPEN SOURCE': 'OPEN SOURCE',
    'Inspect the control plane you trust with the machine.': 'Prüfe die Steuerungsebene, der du deine Maschine anvertraust.',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'ThreadCells steht unter der Apache License 2.0; die Herkunftsangaben zum Upstream bleiben in den entsprechenden Rechts- und Herkunftsdokumenten erhalten.',
    'Stop guessing what the agents are doing.': 'Rätsel nicht länger, was die Agenten tun.',
    'Run the work. See the machine. Keep the result.': 'Führe die Arbeit aus. Sieh den Zustand der Maschine. Bewahre das Ergebnis.',
    'Open Quick Setup': 'Quick Setup öffnen',
  },
  signals: ['KOORDINIERTE WORKFLOWS', 'GESCHÜTZTES HOUSEKEEPING', 'DAUERHAFTER VERLAUF', 'LOOPBACK ZUERST'],
  capabilities: [
    { title: 'Tatsächlicher Betriebszustand', copy: 'Sieh, was resident, aktiv, wartend, im Abbau, blockiert oder wirklich abgeschlossen ist, ohne den Zustand aus einem Terminal-Tab abzuleiten.' },
    { title: 'Worktree-Berechtigung', copy: 'Binde Arbeit an vertrauenswürdige Projekte und verwaltete Git-Worktrees. Schreibberechtigungen machen gleichzeitige Änderungen ausdrücklich sichtbar.' },
    { title: 'Dauerhafte Ergebnisse', copy: 'Delegierte Arbeit liefert ein gespeichertes Ergebnis, das ohne Verlust des Verlaufs zugestellt, bestätigt, angenommen und aus der aktiven Umgebung entfernt werden kann.' },
    { title: 'Eine gesunde Agentenumgebung', copy: 'ThreadCells überwacht den Hostdruck und entfernt geeignete Laufzeit-, Protokoll-, Cache-, Build- und Release-Reste sicher, während aktive Arbeit und dauerhafter Verlauf geschützt bleiben.' },
  ],
  steps: [
    { title: 'Sitzung erstellen', copy: 'Wähle ein vertrauenswürdiges lokales Projekt und ein Agenten- oder Supervisor-Profil.' },
    { title: 'Aufgabe übergeben', copy: 'Ein Supervisor kann zusammenhängende Arbeit an native CLI-Worker und Reviewer delegieren.' },
    { title: 'System beobachten', copy: 'ThreadCells führt den Workflow über Modell-Turns hinweg fort, während Sitzungen, Worktrees, Kapazitäten und Hostdruck sichtbar bleiben.' },
    { title: 'Bei Bedarf eingreifen', copy: 'Ergebnisse bleiben dauerhaft erhalten. Eine Owner-Entscheidung hält den Workflow nur an, wenn du wirklich gebraucht wirst.' },
  ],
  jsonLdFeatures: [
    'Persistente Sitzungen nativer CLI-Agenten',
    'Verwaltete Git-Worktrees und Schreibberechtigungen',
    'Dauerhafte Ergebnisse delegierter Arbeit',
    'Expliziter Workflow-Lebenszyklus und Owner-Entscheidungen',
    'Unabhängige Steuerung der Ausführungskapazitäten',
    'Housekeeping unter Beachtung der geschützten Menge und Entfernung geschlossener Laufzeiten',
    'Optionale installationsweite Telegram-Benachrichtigungen zum Lebenszyklus',
  ],
}
