import type { LandingLocaleData } from './types'

export const esLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': 'AUTOALOJADO',
    'CODING-AGENT OPERATIONS': 'OPERACIONES DE AGENTES DE PROGRAMACIÓN',
    'Work with AI agents ': 'Trabaja con agentes de IA ',
    'as a system': 'como un sistema',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'ThreadCells coordina agentes de CLI nativos, mantiene los flujos abiertos en marcha entre turnos del modelo y cuida el entorno de orquestación que los sustenta, en tu propio host Linux.',
    'View on GitHub': 'Ver en GitHub',
    'Read the docs': 'Leer la documentación',
    'Start the work. Watch the system. Step in only when it needs you.': 'Inicia el trabajo. Observa el sistema. Intervén solo cuando te necesite.',
    'CONTROL / RESULT': 'CONTROL / RESULTADO',
    'ThreadCells operating principles': 'Principios operativos de ThreadCells',
    'THE HARD PART': 'LA PARTE DIFÍCIL',
    'Starting more agents is easy.': 'Iniciar más agentes es fácil.',
    'Knowing what is true is not.': 'Saber qué ocurre de verdad no lo es.',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': '¿Qué proceso controla el worktree? ¿Qué sesión está inactiva y cuál ha terminado? ¿La máquina se quedó sin capacidad del proveedor, contextos de trabajo o ejecución pesada? ¿El revisor devolvió un resultado o solo dejó de mostrar salida?',
    'Operational questions ThreadCells answers': 'Preguntas operativas que responde ThreadCells',
    'SUPERVISOR': 'SUPERVISOR',
    'RUNNING': 'EN EJECUCIÓN',
    'provider 01 / 03': 'proveedor 01 / 03',
    'WORKER': 'EJECUTOR',
    'COMPLETE': 'COMPLETO',
    'result persisted': 'resultado persistido',
    'REVIEWER': 'REVISOR',
    'READY': 'LISTO',
    'context 02 / 02': 'contexto 02 / 02',
    'OWNER GATE': 'DECISIÓN DEL PROPIETARIO',
    'AUTHORITY': 'AUTORIDAD',
    'GATED': 'EN ESPERA',
    'decision required': 'se requiere una decisión',
    'THE CONTROL PLANE': 'EL PLANO DE CONTROL',
    'One place to see the work,': 'Un solo lugar para ver el trabajo,',
    'the host, and the handoff.': 'el host y la entrega.',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'ThreadCells reúne la ejecución nativa de agentes en una superficie operativa: sesiones, proyectos, terminales, perfiles, capacidad, flujos, documentación, alertas globales opcionales de Telegram y la identidad de la compilación actual.',
    'ThreadCells Home showing 21 real sessions, 166 agents, aggregate lifecycle counts, and dense session status summaries': 'Inicio de ThreadCells con 21 sesiones reales, 166 agentes, recuentos agregados del ciclo de vida y resúmenes detallados del estado de las sesiones',
    'HOME / EXECUTION OVERVIEW': 'INICIO / RESUMEN DE EJECUCIÓN',
    'Real release system · sensitive material excluded': 'Sistema de publicación real · contenido sensible excluido',
    'LIVE RELEASE SYSTEM': 'SISTEMA DE PUBLICACIÓN ACTIVO',
    'LIVE RELEASE SYSTEM · IDENTITIES ANONYMIZED': 'SISTEMA DE PUBLICACIÓN ACTIVO · IDENTIDADES ANONIMIZADAS',
    'Session truth': 'Estado real de la sesión',
    'Provider, profile, lifecycle, project, and active work remain visible.': 'El proveedor, el perfil, el ciclo de vida, el proyecto y el trabajo activo siguen visibles.',
    'Operational scale': 'Operación a escala',
    'First, Last, and Total summaries keep large durable histories readable.': 'Los resúmenes Primero, Último y Total mantienen legibles los historiales duraderos de gran tamaño.',
    'CORE IDEAS': 'IDEAS PRINCIPALES',
    'A control room built around': 'Una sala de control diseñada para',
    'the failure modes that matter.': 'los fallos que importan.',
    'WORKFLOW': 'FLUJO DE TRABAJO',
    'Intent goes out.': 'La intención sale.',
    'Evidence comes back.': 'La evidencia vuelve.',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': 'El agente de programación sigue siendo nativo. ThreadCells hace explícito el ciclo de vida que lo rodea.',
    'LIVE RELEASE TOUR': 'RECORRIDO DEL SISTEMA REAL',
    'See the control plane in motion.': 'Mira el plano de control en funcionamiento.',
    'A tour of the real release system: Home, multi-agent work, Agents, provider-reported Statistics, Housekeeping, capacity, and redacted notification settings. Operational values and lifecycle states are real; Session and Project labels are anonymized.': 'Un recorrido por el sistema de publicación real: Inicio, trabajo multiagente, Agents, estadísticas informadas por el proveedor, Housekeeping, capacidad y ajustes de notificaciones censurados. Los valores operativos y los estados del ciclo de vida son reales; los nombres de Session y Project están anonimizados.',
    'THREADCELLS / LIVE DATA · IDENTITIES ANONYMIZED': 'THREADCELLS / DATOS REALES · IDENTIDADES ANONIMIZADAS',
    'Live ThreadCells release-system tour': 'Recorrido por el sistema de publicación activo de ThreadCells',
    'The demo video is unavailable in this browser.': 'El vídeo de demostración no está disponible en este navegador.',
    'PRODUCT EXPERIENCE': 'EXPERIENCIA DEL PRODUCTO',
    'The workflow and the host,': 'El flujo y el host,',
    'in one operating view.': 'en una sola vista operativa.',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': 'Abre la sesión real detrás del resumen, conserva un runtime saludable y dirige al propietario solo las decisiones importantes sin perder el contexto duradero.',
    'Expanded live ThreadCells session with processing and recovery-replaced agents': 'Sesión activa de ThreadCells desplegada con un agente en proceso y otro reemplazado durante la recuperación',
    'SESSION / MULTI-AGENT WORKFLOW': 'SESIÓN / FLUJO MULTIAGENTE',
    'Real lifecycle state and durable recovery evidence': 'Estados reales del ciclo de vida y evidencia duradera de recuperación',
    'ThreadCells Agents showing mixed lifecycle states and a stable action row': 'Agents de ThreadCells con distintos estados del ciclo de vida y una fila de acciones estable',
    'AGENTS / LIFECYCLE CONTROL': 'AGENTES / CONTROL DEL CICLO DE VIDA',
    'Status, profile, workflow, and actions stay aligned': 'El estado, el perfil, el workflow y las acciones se mantienen alineados',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'Housekeeping de ThreadCells con salud del disco, copias protegidas, programación y política de limpieza',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / CUIDADO DEL SERVIDOR',
    'Plan, revalidate, protect active work': 'Planificar, volver a validar y proteger el trabajo activo',
    'ThreadCells Orchestration Capacity showing independent execution limits and host pressure': 'Capacidad de orquestación de ThreadCells con límites de ejecución independientes y presión del host',
    'CAPACITY / HOST ADMISSION': 'CAPACIDAD / ADMISIÓN DEL HOST',
    'Resident, provider, work, and heavy limits stay independent': 'Los límites de residentes, proveedores, trabajo y ejecución pesada permanecen independientes',
    'ThreadCells Statistics showing provider-reported token usage by session and profile': 'Estadísticas de ThreadCells con el uso de tokens informado por el proveedor, por sesión y perfil',
    'STATISTICS / PROVIDER TELEMETRY': 'ESTADÍSTICAS / TELEMETRÍA DEL PROVEEDOR',
    'Reported values stay separate from unknown data': 'Los valores informados se mantienen separados de los datos desconocidos',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': 'Ajustes de notificaciones de Telegram en ThreadCells con los campos de destino y credenciales visiblemente ocultos',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / ATENCIÓN DEL PROPIETARIO',
    'One low-noise installation-global route': 'Un canal global de bajo ruido para toda la instalación',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': 'SISTEMA ACTIVO · CAMPOS SENSIBLES OCULTOS',
    'project authority resolved': 'autoridad del proyecto resuelta',
    'provider capacity admitted': 'capacidad del proveedor admitida',
    'session cao-atlas-control started': 'sesión cao-atlas-control iniciada',
    'resident': 'residente',
    'provider': 'proveedor',
    'work context': 'contexto de trabajo',
    'heavy': 'ejecución pesada',
    'NATIVE BY DESIGN': 'NATIVO POR DISEÑO',
    'Keep the coding agent.': 'Conserva tu agente de programación.',
    'Add the operating system around it.': 'Añade el sistema operativo que lo rodea.',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'ThreadCells controla las CLI nativas de los proveedores en terminales tmux reales. Los adaptadores informan de lo que el host instalado admite de verdad; las funciones no compatibles se muestran como tales en lugar de simularse.',
    'Codex reference adapter and first-class Claude Code adapter': 'Adaptador de referencia para Codex y adaptador de primera clase para Claude Code',
    'Provider-native authentication remains with the operator': 'La autenticación nativa del proveedor permanece bajo control del operador',
    'Profiles and provider configuration are versioned control-plane artifacts': 'Los perfiles y la configuración del proveedor son artefactos versionados del plano de control',
    'TECHNICAL PREVIEW': 'VERSIÓN PRELIMINAR TÉCNICA',
    'A practical first run.': 'Un primer inicio práctico.',
    'Honest alpha boundaries.': 'Límites claros de la versión alfa.',
    'ThreadCells is for individual developers and trusted small teams that operate several coding agents on one Linux host and want durable workflow state instead of a pile of terminal tabs.': 'ThreadCells está pensado para desarrolladores individuales y pequeños equipos de confianza que operan varios agentes de código en un único host Linux y prefieren un estado de workflow duradero a una pila de pestañas de terminal.',
    'Start on a trusted Linux host': 'Empieza en un host Linux de confianza',
    'The supported baseline is Ubuntu or Debian with Python 3, Git, tmux, Node.js/npm for the Web build, and at least one provider CLI you have authenticated.': 'La base compatible es Ubuntu o Debian con Python 3, Git, tmux, Node.js/npm para compilar la interfaz web y al menos una CLI de proveedor en la que hayas iniciado sesión.',
    'Open the installation guide': 'Abrir la guía de instalación',
    'Provider support stays explicit': 'La compatibilidad de proveedores es explícita',
    'Eight built-in adapters normalize launch and lifecycle. Codex is the release-acceptance reference; readiness, resume, usage, and model controls still depend on the installed provider CLI.': 'Ocho adaptadores integrados normalizan el inicio y el ciclo de vida. Codex es la referencia para aceptar una versión; la disponibilidad, la reanudación, el uso y los controles del modelo siguen dependiendo de la CLI de proveedor instalada.',
    'Check provider compatibility': 'Comprobar la compatibilidad de proveedores',
    'Know where trust stops': 'Conoce los límites de confianza',
    'This alpha targets one trusted operator and one host. It is loopback-first, supports remote use through an SSH tunnel, and does not treat worktrees as security sandboxes or isolate hostile tenants.': 'Esta versión alfa está dirigida a un operador de confianza y un solo host. Prioriza loopback, admite el uso remoto mediante un túnel SSH y no considera los worktrees como entornos aislados de seguridad ni aísla usuarios que no confían entre sí.',
    'Read the alpha limitations': 'Leer las limitaciones de la versión alfa',
    'MACHINE OWNERSHIP': 'PROPIEDAD DE LA MÁQUINA',
    'Your host.': 'Tu host.',
    'Your terminals.': 'Tus terminales.',
    'Your control.': 'Tu control.',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'ThreadCells es autoalojado y prioriza loopback. Coordina herramientas locales potentes, pero no presenta un worktree como aislamiento de seguridad ni promete multitenencia entre usuarios que no confían entre sí.',
    'Loopback first': 'Loopback primero',
    'SSH-tunnel access is the supported preview boundary.': 'El túnel SSH es el límite de acceso admitido durante la vista previa.',
    'Real terminals': 'Terminales reales',
    'Inspectable tmux sessions, not hidden disposable jobs.': 'Sesiones tmux que puedes inspeccionar, no tareas ocultas y desechables.',
    'OPEN SOURCE': 'CÓDIGO ABIERTO',
    'Inspect the control plane you trust with the machine.': 'Inspecciona el plano de control al que confías tu máquina.',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'ThreadCells está disponible bajo Apache License 2.0 y conserva la atribución del proyecto de origen en los materiales legales y de procedencia correspondientes.',
    'Stop guessing what the agents are doing.': 'Deja de adivinar qué hacen los agentes.',
    'Run the work. See the machine. Keep the result.': 'Ejecuta el trabajo. Observa la máquina. Conserva el resultado.',
    'Open Quick Setup': 'Abrir Quick Setup',
  },
  signals: ['FLUJOS COORDINADOS', 'HOUSEKEEPING PROTEGIDO', 'HISTORIAL DURADERO', 'LOOPBACK PRIMERO'],
  capabilities: [
    { title: 'Estado operativo real', copy: 'Comprueba qué permanece residente, se ejecuta, espera, se retira, está bloqueado o ha terminado de verdad, sin deducirlo de una pestaña de terminal.' },
    { title: 'Autoridad del worktree', copy: 'Vincula el trabajo a proyectos de confianza y Git worktrees gestionados. Los permisos de escritura hacen explícitas las modificaciones concurrentes.' },
    { title: 'Resultados duraderos', copy: 'El trabajo delegado devuelve un resultado persistente que se puede entregar, confirmar, aceptar y retirar sin perder el historial.' },
    { title: 'Un entorno saludable para agentes', copy: 'ThreadCells vigila la presión del host y limpia de forma segura runtimes, registros, cachés, compilaciones y publicaciones aptos, sin tocar el trabajo activo ni el historial duradero.' },
  ],
  steps: [
    { title: 'Crea una sesión', copy: 'Elige un proyecto local de confianza y un perfil de agente o supervisor.' },
    { title: 'Encarga el trabajo', copy: 'Un supervisor puede delegar unidades coherentes en ejecutores y revisores de CLI nativos.' },
    { title: 'Observa el sistema', copy: 'ThreadCells mantiene el flujo en marcha entre turnos del modelo mientras las sesiones, los worktrees, la capacidad y la presión del host siguen visibles.' },
    { title: 'Intervén cuando te lo pida', copy: 'Los resultados se guardan de forma duradera. Las decisiones del propietario solo detienen el flujo cuando realmente te necesitan.' },
  ],
  jsonLdFeatures: [
    'Sesiones persistentes de agentes de CLI nativos',
    'Git worktrees gestionados y autoridad de escritura',
    'Resultados delegados duraderos',
    'Ciclo de vida explícito de los flujos y decisiones del propietario',
    'Controles independientes de capacidad de ejecución',
    'Housekeeping que respeta el conjunto protegido y retiro de runtimes cerrados',
    'Notificaciones globales opcionales de Telegram para el ciclo de vida de la instalación',
  ],
}
