import type { LandingLocaleData } from './types'

export const jaLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': 'セルフホスト',
    'CODING-AGENT OPERATIONS': 'コーディングエージェント運用',
    'Work with AI agents ': 'AI エージェントを',
    'as a system': 'ひとつのシステムとして運用',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'ThreadCells は自分の Linux ホスト上でネイティブ CLI エージェントを連携させ、モデルのターンをまたいでオープンなワークフローを進め、その基盤となるオーケストレーション環境を維持します。',
    'View on GitHub': 'GitHub で見る',
    'Read the docs': 'ドキュメントを読む',
    'Start the work. Watch the system. Step in only when it needs you.': '作業を開始し、システムを見守り、必要なときだけ介入します。',
    'CONTROL / RESULT': '制御 / 結果',
    'ThreadCells operating principles': 'ThreadCells の運用原則',
    'THE HARD PART': '本当に難しいこと',
    'Starting more agents is easy.': 'エージェントを増やすのは簡単です。',
    'Knowing what is true is not.': '実際の状態を把握するのは簡単ではありません。',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': 'どのプロセスが worktree を所有しているのか。どのセッションが単にアイドルで、どれが終了したのか。足りないのはプロバイダー容量、作業コンテキスト、重い実行枠のどれか。レビュアーは結果を返したのか、それとも出力が止まっただけなのか。',
    'Operational questions ThreadCells answers': 'ThreadCells が答える運用上の問い',
    'SUPERVISOR': 'スーパーバイザー',
    'RUNNING': '実行中',
    'provider 01 / 03': 'プロバイダー 01 / 03',
    'WORKER': 'ワーカー',
    'COMPLETE': '完了',
    'result persisted': '結果を永続化',
    'REVIEWER': 'レビュアー',
    'READY': '準備完了',
    'context 02 / 02': 'コンテキスト 02 / 02',
    'OWNER GATE': 'オーナーゲート',
    'AUTHORITY': '権限',
    'GATED': '判断待ち',
    'decision required': '判断が必要',
    'THE CONTROL PLANE': 'コントロールプレーン',
    'One place to see the work,': '作業、ホスト、引き継ぎを',
    'the host, and the handoff.': 'ひとつの画面で把握。',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'ThreadCells はネイティブなエージェント実行を、セッション、プロジェクト、ターミナル、プロファイル、容量、ワークフロー、ドキュメント、任意のインストール全体 Telegram ライフサイクル通知、現在のビルド識別子を含む運用画面にまとめます。',
    'ThreadCells Home showing 21 real sessions, 166 agents, aggregate lifecycle counts, and dense session status summaries': '21 の実セッション、166 のエージェント、ライフサイクル集計、詳細なセッション状態を表示する ThreadCells ホーム',
    'HOME / EXECUTION OVERVIEW': 'ホーム / 実行概要',
    'Real release system · sensitive material excluded': '実際のリリースシステム · 機密情報は除外',
    'LIVE RELEASE SYSTEM': '稼働中のリリースシステム',
    'Session truth': 'セッションの実状態',
    'Provider, profile, lifecycle, project, and active work remain visible.': 'プロバイダー、プロファイル、ライフサイクル、プロジェクト、進行中の作業を常に確認できます。',
    'Operational scale': '大規模な運用',
    'First, Last, and Total summaries keep large durable histories readable.': '最初、最新、合計の要約により、大量の永続履歴も読みやすく保てます。',
    'CORE IDEAS': '中核となる考え方',
    'A control room built around': '重要な障害モードを中心に',
    'the failure modes that matter.': '設計されたコントロールルーム。',
    'WORKFLOW': 'ワークフロー',
    'Intent goes out.': '意図を送り出す。',
    'Evidence comes back.': '証拠が戻ってくる。',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': 'コーディングエージェントはネイティブのまま。ThreadCells が周囲のライフサイクルを明確にします。',
    'LIVE RELEASE TOUR': '実環境ツアー',
    'See the control plane in motion.': '動作するコントロールプレーンを見る。',
    'A short tour through the real release system: dense Home state, an expanded multi-agent session, protected Housekeeping, and independent capacity.': '実際のリリースシステムを短く紹介します。情報量の多いホーム、展開したマルチエージェントセッション、保護された Housekeeping、独立した各容量を確認できます。',
    'THREADCELLS / LIVE RELEASE SYSTEM': 'THREADCELLS / 稼働中のリリースシステム',
    'Live ThreadCells release-system tour': '稼働中の ThreadCells リリースシステムのツアー',
    'The demo video is unavailable in this browser.': 'このブラウザーではデモ動画を再生できません。',
    'PRODUCT EXPERIENCE': '製品体験',
    'The workflow and the host,': 'ワークフローとホストを',
    'in one operating view.': 'ひとつの運用画面に。',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': '要約の背後にある実セッションを開き、ランタイムを健全に保ち、永続コンテキストを失わずに重要な事項だけをオーナーへ届けます。',
    'Expanded live ThreadCells session with one active owner and two completed reviewers': '1 人のアクティブなオーナーと作業を完了した 2 人のレビュアーを表示する ThreadCells 実セッション',
    'SESSION / MULTI-AGENT WORKFLOW': 'セッション / マルチエージェントワークフロー',
    'Real profiles, lifecycle, and durable completion': '実際のプロファイル、ライフサイクル、永続的な完了状態',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'ディスク状態、保護されたバックアップ、スケジュール、クリーンアップポリシーを表示する ThreadCells Housekeeping',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / サーバー管理',
    'Plan, revalidate, protect active work': '計画し、再検証し、進行中の作業を保護',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': '宛先と認証情報を明示的に伏せた ThreadCells Telegram 通知設定',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / オーナーへの通知',
    'One low-noise installation-global route': 'インストール全体で使う低ノイズの通知経路',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': '稼働中のシステム · 機密フィールドは伏せ字',
    'project authority resolved': 'プロジェクト権限を解決',
    'provider capacity admitted': 'プロバイダー容量を確保',
    'session cao-atlas-control started': 'セッション cao-atlas-control を開始',
    'resident': '常駐',
    'provider': 'プロバイダー',
    'work context': '作業コンテキスト',
    'heavy': '重い実行',
    'NATIVE BY DESIGN': 'ネイティブを前提に設計',
    'Keep the coding agent.': '使い慣れたコーディングエージェントはそのまま。',
    'Add the operating system around it.': '周囲に運用システムを加える。',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'ThreadCells は実際の tmux ターミナルでプロバイダーのネイティブ CLI を動かします。プロバイダーアダプターはインストール先ホストが本当に対応する機能だけを報告し、非対応の機能を模擬せず明示します。',
    'Codex reference adapter and first-class Claude Code adapter': 'Codex リファレンスアダプターと第一級の Claude Code アダプター',
    'Provider-native authentication remains with the operator': 'プロバイダー固有の認証はオペレーターが管理',
    'Profiles and provider configuration are versioned control-plane artifacts': 'プロファイルとプロバイダー設定はバージョン管理されたコントロールプレーン成果物',
    'MACHINE OWNERSHIP': 'マシンの所有権',
    'Your host.': '自分のホスト。',
    'Your terminals.': '自分のターミナル。',
    'Your control.': '自分で制御。',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'ThreadCells はセルフホストで、loopback を優先します。強力なローカルツールを連携しますが、worktree をセキュリティサンドボックスとして扱ったり、相互に信頼しないマルチテナント環境を保証したりはしません。',
    'Loopback first': 'loopback を優先',
    'SSH-tunnel access is the supported preview boundary.': 'プレビュー版で対応するアクセス境界は SSH トンネルです。',
    'Real terminals': '実際のターミナル',
    'Inspectable tmux sessions, not hidden disposable jobs.': '隠れた使い捨てジョブではなく、確認できる tmux セッションです。',
    'OPEN SOURCE': 'オープンソース',
    'Inspect the control plane you trust with the machine.': 'マシンを託すコントロールプレーンを自分で確認できます。',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'ThreadCells は Apache License 2.0 で提供され、上流への帰属表示は該当する法的資料と来歴資料に保持されています。',
    'Stop guessing what the agents are doing.': 'エージェントの動作を推測するのは終わりにしましょう。',
    'Run the work. See the machine. Keep the result.': '作業を実行し、マシンを把握し、結果を残す。',
    'Open Quick Setup': 'Quick Setup を開く',
  },
  signals: ['連携するワークフロー', '保護された HOUSEKEEPING', '永続履歴', 'LOOPBACK 優先'],
  capabilities: [
    { title: '運用上の実状態', copy: '常駐、実行、待機、終了処理中、ブロック、本当の完了を、ターミナルタブから推測せず確認できます。' },
    { title: 'Worktree の権限', copy: '作業を信頼済みプロジェクトと管理対象 Git worktree に結び付けます。書き込みリースにより並行変更の権限が明確になります。' },
    { title: '永続的な結果', copy: '委任した作業の結果を永続化し、履歴を失わずに配信、確認、受け入れ、アクティブ環境からの退役ができます。' },
    { title: '健全なエージェント環境', copy: 'ThreadCells はホスト負荷を監視し、進行中の作業と永続履歴を保護しながら、対象となるランタイム、ログ、キャッシュ、ビルド、リリースの残骸を安全に整理します。' },
  ],
  steps: [
    { title: 'セッションを作成', copy: '信頼済みローカルプロジェクトと、エージェントまたはスーパーバイザーのプロファイルを選びます。' },
    { title: '作業を依頼', copy: 'スーパーバイザーが一貫した作業単位をネイティブ CLI ワーカーとレビュアーへ委任できます。' },
    { title: 'システムを監視', copy: 'ThreadCells はモデルのターンをまたいでワークフローを進め、セッション、worktree、容量、ホスト負荷を見える状態に保ちます。' },
    { title: '必要なときだけ介入', copy: '結果は永続化されます。本当に判断が必要な場合だけ、オーナーゲートがワークフローを一時停止します。' },
  ],
  jsonLdFeatures: [
    '永続的なネイティブ CLI エージェントセッション',
    '管理対象 Git worktree と書き込み権限',
    '永続化された委任結果',
    '明示的なワークフローライフサイクルとオーナーゲート',
    '独立した実行容量制御',
    '保護対象を考慮した Housekeeping と終了済みランタイムの退役',
    '任意のインストール全体 Telegram ライフサイクル通知',
  ],
}
