import type { LandingLocaleData } from './types'

export const jaLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': 'セルフホスト',
    'CODING-AGENT OPERATIONS': 'コーディングエージェント運用',
    'Work with AI agents ': 'AI エージェントを',
    'as a system': 'ひとつのシステムとして運用',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'ThreadCells は自分の Linux ホスト上でネイティブ CLI エージェントを連携させ、モデルのターンをまたいでオープンなワークフローを進め、その基盤となるオーケストレーション環境を維持します。',
    'View on GitHub': 'GitHub で見る',
    'Read the docs': 'ドキュメントを読む',
    'Start the work. Watch the system. Step in only when it needs you.': '作業を開始し、システムを見守り、必要なときだけ介入します。',
    'CONTROL / RESULT': '制御 / 結果',
    'ThreadCells operating principles': 'ThreadCells の運用原則',
    'THE HARD PART': '本当に難しいこと',
    'Starting more agents is easy.': 'エージェントを増やすのは簡単です。',
    'Knowing what is true is not.': '実際の状態を把握するのは簡単ではありません。',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': 'どのプロセスが worktree を所有しているのか。どのセッションが単にアイドルで、どれが終了したのか。足りないのはプロバイダー容量、作業コンテキスト、重い実行枠のどれか。レビュアーは結果を返したのか、それとも出力が止まっただけなのか。',
    'Operational questions ThreadCells answers': 'ThreadCells が答える運用上の問い',
    'SUPERVISOR': 'スーパーバイザー',
    'RUNNING': '実行中',
    'provider 01 / 03': 'プロバイダー 01 / 03',
    'WORKER': 'ワーカー',
    'COMPLETE': '完了',
    'result persisted': '結果を永続化',
    'REVIEWER': 'レビュアー',
    'READY': '準備完了',
    'context 02 / 02': 'コンテキスト 02 / 02',
    'OWNER GATE': 'オーナーゲート',
    'AUTHORITY': '権限',
    'GATED': '判断待ち',
    'decision required': '判断が必要',
    'THE CONTROL PLANE': 'コントロールプレーン',
    'One place to see the work,': '作業、ホスト、引き継ぎを',
    'the host, and the handoff.': 'ひとつの画面で把握。',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'ThreadCells はネイティブなエージェント実行を、セッション、プロジェクト、ターミナル、プロファイル、容量、ワークフロー、ドキュメント、任意のインストール全体 Telegram ライフサイクル通知、現在のビルド識別子を含む運用画面にまとめます。',
    'ThreadCells Home showing 21 real sessions, 166 agents, aggregate lifecycle counts, and dense session status summaries': '21 の実セッション、166 のエージェント、ライフサイクル集計、詳細なセッション状態を表示する ThreadCells ホーム',
    'HOME / EXECUTION OVERVIEW': 'ホーム / 実行概要',
    'Real release system · sensitive material excluded': '実際のリリースシステム · 機密情報は除外',
    'LIVE RELEASE SYSTEM': '稼働中のリリースシステム',
    'LIVE RELEASE SYSTEM · IDENTITIES ANONYMIZED': '稼働中のリリースシステム · ID は匿名化済み',
    'Session truth': 'セッションの実状態',
    'Provider, profile, lifecycle, project, and active work remain visible.': 'プロバイダー、プロファイル、ライフサイクル、プロジェクト、進行中の作業を常に確認できます。',
    'Operational scale': '大規模な運用',
    'First, Last, and Total summaries keep large durable histories readable.': '最初、最新、合計の要約により、大量の永続履歴も読みやすく保てます。',
    'CORE IDEAS': '中核となる考え方',
    'A control room built around': '重要な障害モードを中心に',
    'the failure modes that matter.': '設計されたコントロールルーム。',
    'WORKFLOW': 'ワークフロー',
    'Intent goes out.': '意図を送り出す。',
    'Evidence comes back.': '証拠が戻ってくる。',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': 'コーディングエージェントはネイティブのまま。ThreadCells が周囲のライフサイクルを明確にします。',
    'LIVE RELEASE TOUR': '実環境ツアー',
    'See the control plane in motion.': '動作するコントロールプレーンを見る。',
    'A tour of the real release system: Home, multi-agent work, Agents, provider-reported Statistics, Housekeeping, capacity, and redacted notification settings. Operational values and lifecycle states are real; Session and Project labels are anonymized.': '実際のリリースシステムを紹介します。ホーム、マルチエージェント作業、Agents、プロバイダー報告の統計、Housekeeping、容量、編集済みの通知設定を確認できます。運用値とライフサイクル状態は実データで、Session と Project の名前は匿名化されています。',
    'THREADCELLS / LIVE DATA · IDENTITIES ANONYMIZED': 'THREADCELLS / 実データ · ID は匿名化済み',
    'Live ThreadCells release-system tour': '稼働中の ThreadCells リリースシステムのツアー',
    'The demo video is unavailable in this browser.': 'このブラウザーではデモ動画を再生できません。',
    'PRODUCT EXPERIENCE': '製品体験',
    'The workflow and the host,': 'ワークフローとホストを',
    'in one operating view.': 'ひとつの運用画面に。',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': '要約の背後にある実セッションを開き、ランタイムを健全に保ち、永続コンテキストを失わずに重要な事項だけをオーナーへ届けます。',
    'Expanded live ThreadCells session with processing and recovery-replaced agents': '処理中のエージェントと復旧時に置き換えられたエージェントを示す、展開されたライブ ThreadCells セッション',
    'SESSION / MULTI-AGENT WORKFLOW': 'セッション / マルチエージェントワークフロー',
    'Real lifecycle state and durable recovery evidence': '実際のライフサイクル状態と永続化された復旧証跡',
    'ThreadCells Agents showing mixed lifecycle states and a stable action row': '複数のライフサイクル状態と安定した操作列を表示する ThreadCells Agents',
    'AGENTS / LIFECYCLE CONTROL': 'エージェント / ライフサイクル制御',
    'Status, profile, workflow, and actions stay aligned': '状態、プロファイル、ワークフロー、操作の配置を統一',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'ディスク状態、保護されたバックアップ、スケジュール、クリーンアップポリシーを表示する ThreadCells Housekeeping',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / サーバー管理',
    'Plan, revalidate, protect active work': '計画し、再検証し、進行中の作業を保護',
    'ThreadCells Orchestration Capacity showing independent execution limits and host pressure': '独立した実行上限とホスト負荷を表示する ThreadCells Orchestration Capacity',
    'CAPACITY / HOST ADMISSION': '容量 / ホストへの受け入れ',
    'Resident, provider, work, and heavy limits stay independent': '常駐、プロバイダー、作業、高負荷の上限をそれぞれ独立して管理',
    'ThreadCells Statistics showing provider-reported token usage by session and profile': 'プロバイダーが報告したトークン使用量をセッションとプロファイル別に表示する ThreadCells Statistics',
    'STATISTICS / PROVIDER TELEMETRY': '統計 / プロバイダーテレメトリー',
    'Reported values stay separate from unknown data': '報告された値と不明なデータを分けて表示',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': '宛先と認証情報を明示的に伏せた ThreadCells Telegram 通知設定',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / オーナーへの通知',
    'One low-noise installation-global route': 'インストール全体で使う低ノイズの通知経路',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': '稼働中のシステム · 機密フィールドは伏せ字',
    'project authority resolved': 'プロジェクト権限を解決',
    'provider capacity admitted': 'プロバイダー容量を確保',
    'session cao-atlas-control started': 'セッション cao-atlas-control を開始',
    'resident': '常駐',
    'provider': 'プロバイダー',
    'work context': '作業コンテキスト',
    'heavy': '重い実行',
    'NATIVE BY DESIGN': 'ネイティブを前提に設計',
    'Keep the coding agent.': '使い慣れたコーディングエージェントはそのまま。',
    'Add the operating system around it.': '周囲に運用システムを加える。',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'ThreadCells は実際の tmux ターミナルでプロバイダーのネイティブ CLI を動かします。プロバイダーアダプターはインストール先ホストが本当に対応する機能だけを報告し、非対応の機能を模擬せず明示します。',
    'Codex reference adapter and first-class Claude Code adapter': 'Codex リファレンスアダプターと第一級の Claude Code アダプター',
    'Provider-native authentication remains with the operator': 'プロバイダー固有の認証はオペレーターが管理',
    'Profiles and provider configuration are versioned control-plane artifacts': 'プロファイルとプロバイダー設定はバージョン管理されたコントロールプレーン成果物',
    'TECHNICAL PREVIEW': 'テクニカルプレビュー',
    'A practical first run.': '実用的な最初の一歩。',
    'Honest alpha boundaries.': 'アルファ版の境界を正直に。',
    'ThreadCells is for individual developers and trusted small teams that operate several coding agents on one Linux host and want durable workflow state instead of a pile of terminal tabs.': 'ThreadCells は、1 台の Linux ホストで複数のコーディングエージェントを運用し、積み重なったターミナルタブではなく永続的なワークフロー状態を必要とする個人開発者や信頼できる小規模チーム向けです。',
    'Start on a trusted Linux host': '信頼できる Linux ホストで始める',
    'The supported baseline is Ubuntu or Debian with Python 3, Git, tmux, Node.js/npm for the Web build, and at least one provider CLI you have authenticated.': '対応する基本環境は Ubuntu または Debian です。Python 3、Git、tmux、Web UI のビルド用 Node.js/npm、認証済みのプロバイダー CLI が少なくとも 1 つ必要です。',
    'Open the installation guide': 'インストールガイドを開く',
    'Provider support stays explicit': 'プロバイダー対応を明確に表示',
    'Eight built-in adapters normalize launch and lifecycle. Codex is the release-acceptance reference; readiness, resume, usage, and model controls still depend on the installed provider CLI.': '8 つの組み込みアダプターが起動とライフサイクルを共通化します。Codex はリリース受け入れの基準です。準備状態、再開、使用量、モデル制御は引き続きインストール済みのプロバイダー CLI に依存します。',
    'Check provider compatibility': 'プロバイダー互換性を確認',
    'Know where trust stops': '信頼境界を理解する',
    'This alpha targets one trusted operator and one host. It is loopback-first, supports remote use through an SSH tunnel, and does not treat worktrees as security sandboxes or isolate hostile tenants.': 'このアルファ版は、信頼できる 1 人のオペレーターと 1 台のホストを対象としています。loopback を優先し、SSH トンネル経由のリモート利用に対応しますが、worktree をセキュリティサンドボックスとして扱ったり、相互に信頼しない利用者を隔離したりはしません。',
    'Read the alpha limitations': 'アルファ版の制限を読む',
    'MACHINE OWNERSHIP': 'マシンの所有権',
    'Your host.': '自分のホスト。',
    'Your terminals.': '自分のターミナル。',
    'Your control.': '自分で制御。',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'ThreadCells はセルフホストで、loopback を優先します。強力なローカルツールを連携しますが、worktree をセキュリティサンドボックスとして扱ったり、相互に信頼しないマルチテナント環境を保証したりはしません。',
    'Loopback first': 'loopback を優先',
    'SSH-tunnel access is the supported preview boundary.': 'プレビュー版で対応するアクセス境界は SSH トンネルです。',
    'Real terminals': '実際のターミナル',
    'Inspectable tmux sessions, not hidden disposable jobs.': '隠れた使い捨てジョブではなく、確認できる tmux セッションです。',
    'OPEN SOURCE': 'オープンソース',
    'Inspect the control plane you trust with the machine.': 'マシンを託すコントロールプレーンを自分で確認できます。',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'ThreadCells は Apache License 2.0 で提供され、上流への帰属表示は該当する法的資料と来歴資料に保持されています。',
    'Stop guessing what the agents are doing.': 'エージェントの動作を推測するのは終わりにしましょう。',
    'Run the work. See the machine. Keep the result.': '作業を実行し、マシンを把握し、結果を残す。',
    'Open Quick Setup': 'Quick Setup を開く',
  },
  signals: ['連携するワークフロー', '保護された HOUSEKEEPING', '永続履歴', 'LOOPBACK 優先'],
  capabilities: [
    { title: '運用上の実状態', copy: '常駐、実行、待機、終了処理中、ブロック、本当の完了を、ターミナルタブから推測せず確認できます。' },
    { title: 'Worktree の権限', copy: '作業を信頼済みプロジェクトと管理対象 Git worktree に結び付けます。書き込みリースにより並行変更の権限が明確になります。' },
    { title: '永続的な結果', copy: '委任した作業の結果を永続化し、履歴を失わずに配信、確認、受け入れ、アクティブ環境からの退役ができます。' },
    { title: '健全なエージェント環境', copy: 'ThreadCells はホスト負荷を監視し、進行中の作業と永続履歴を保護しながら、対象となるランタイム、ログ、キャッシュ、ビルド、リリースの残骸を安全に整理します。' },
  ],
  steps: [
    { title: 'セッションを作成', copy: '信頼済みローカルプロジェクトと、エージェントまたはスーパーバイザーのプロファイルを選びます。' },
    { title: '作業を依頼', copy: 'スーパーバイザーが一貫した作業単位をネイティブ CLI ワーカーとレビュアーへ委任できます。' },
    { title: 'システムを監視', copy: 'ThreadCells はモデルのターンをまたいでワークフローを進め、セッション、worktree、容量、ホスト負荷を見える状態に保ちます。' },
    { title: '必要なときだけ介入', copy: '結果は永続化されます。本当に判断が必要な場合だけ、オーナーゲートがワークフローを一時停止します。' },
  ],
  jsonLdFeatures: [
    '永続的なネイティブ CLI エージェントセッション',
    '管理対象 Git worktree と書き込み権限',
    '永続化された委任結果',
    '明示的なワークフローライフサイクルとオーナーゲート',
    '独立した実行容量制御',
    '保護対象を考慮した Housekeeping と終了済みランタイムの退役',
    '任意のインストール全体 Telegram ライフサイクル通知',
  ],
}
