import type { LandingLocaleData } from './types'

export const ptBRLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': 'AUTO-HOSPEDADO',
    'CODING-AGENT OPERATIONS': 'OPERAÇÕES DE AGENTES DE PROGRAMAÇÃO',
    'Work with AI agents ': 'Trabalhe com agentes de IA ',
    'as a system': 'como um sistema',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'O ThreadCells coordena agentes de CLI nativos, mantém fluxos abertos avançando entre turnos do modelo e cuida do ambiente de orquestração que os sustenta, no seu próprio host Linux.',
    'View on GitHub': 'Ver no GitHub',
    'Read the docs': 'Ler a documentação',
    'Start the work. Watch the system. Step in only when it needs you.': 'Inicie o trabalho. Observe o sistema. Intervenha apenas quando ele precisar de você.',
    'CONTROL / RESULT': 'CONTROLE / RESULTADO',
    'ThreadCells operating principles': 'Princípios operacionais do ThreadCells',
    'THE HARD PART': 'A PARTE DIFÍCIL',
    'Starting more agents is easy.': 'Iniciar mais agentes é fácil.',
    'Knowing what is true is not.': 'Saber o que realmente acontece não é.',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': 'Qual processo controla o worktree? Qual sessão está apenas ociosa e qual terminou? A máquina ficou sem capacidade do provedor, contextos de trabalho ou execução pesada? O revisor devolveu um resultado ou apenas parou de exibir saída?',
    'Operational questions ThreadCells answers': 'Perguntas operacionais que o ThreadCells responde',
    'SUPERVISOR': 'SUPERVISOR',
    'RUNNING': 'EM EXECUÇÃO',
    'provider 01 / 03': 'provedor 01 / 03',
    'WORKER': 'EXECUTOR',
    'COMPLETE': 'CONCLUÍDO',
    'result persisted': 'resultado persistido',
    'REVIEWER': 'REVISOR',
    'READY': 'PRONTO',
    'context 02 / 02': 'contexto 02 / 02',
    'OWNER GATE': 'DECISÃO DO PROPRIETÁRIO',
    'AUTHORITY': 'AUTORIDADE',
    'GATED': 'AGUARDANDO',
    'decision required': 'decisão necessária',
    'THE CONTROL PLANE': 'O PLANO DE CONTROLE',
    'One place to see the work,': 'Um só lugar para ver o trabalho,',
    'the host, and the handoff.': 'o host e a entrega.',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'O ThreadCells reúne a execução nativa dos agentes em uma superfície operacional: sessões, projetos, terminais, perfis, capacidade, fluxos, documentação, alertas globais opcionais do Telegram e a identidade da compilação atual.',
    'ThreadCells Home showing 21 real sessions, 166 agents, aggregate lifecycle counts, and dense session status summaries': 'Início do ThreadCells mostrando 21 sessões reais, 166 agentes, contagens agregadas do ciclo de vida e resumos detalhados do estado das sessões',
    'HOME / EXECUTION OVERVIEW': 'INÍCIO / VISÃO GERAL DA EXECUÇÃO',
    'Real release system · sensitive material excluded': 'Sistema de lançamento real · conteúdo sensível excluído',
    'LIVE RELEASE SYSTEM': 'SISTEMA DE LANÇAMENTO ATIVO',
    'Session truth': 'Estado real da sessão',
    'Provider, profile, lifecycle, project, and active work remain visible.': 'Provedor, perfil, ciclo de vida, projeto e trabalho ativo continuam visíveis.',
    'Operational scale': 'Operação em escala',
    'First, Last, and Total summaries keep large durable histories readable.': 'Os resumos Primeiro, Último e Total mantêm legíveis os históricos duráveis de grande porte.',
    'CORE IDEAS': 'IDEIAS PRINCIPAIS',
    'A control room built around': 'Uma sala de controle projetada para',
    'the failure modes that matter.': 'as falhas que importam.',
    'WORKFLOW': 'FLUXO DE TRABALHO',
    'Intent goes out.': 'A intenção sai.',
    'Evidence comes back.': 'A evidência volta.',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': 'O agente de programação continua nativo. O ThreadCells deixa explícito todo o ciclo de vida ao redor dele.',
    'LIVE RELEASE TOUR': 'TOUR DO SISTEMA REAL',
    'See the control plane in motion.': 'Veja o plano de controle em funcionamento.',
    'A short tour through the real release system: dense Home state, an expanded multi-agent session, protected Housekeeping, and independent capacity.': 'Um tour rápido pelo sistema de lançamento real: uma página inicial rica em estado, uma sessão multiagente expandida, Housekeeping protegido e capacidades independentes.',
    'THREADCELLS / LIVE RELEASE SYSTEM': 'THREADCELLS / SISTEMA DE LANÇAMENTO ATIVO',
    'Live ThreadCells release-system tour': 'Tour pelo sistema de lançamento ativo do ThreadCells',
    'The demo video is unavailable in this browser.': 'O vídeo de demonstração não está disponível neste navegador.',
    'PRODUCT EXPERIENCE': 'EXPERIÊNCIA DO PRODUTO',
    'The workflow and the host,': 'O fluxo e o host,',
    'in one operating view.': 'em uma única visão operacional.',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': 'Abra a sessão real por trás do resumo, mantenha o runtime saudável e encaminhe ao proprietário apenas as decisões importantes, sem perder o contexto durável.',
    'Expanded live ThreadCells session with one active owner and two completed reviewers': 'Sessão ativa do ThreadCells expandida com um proprietário ativo e dois revisores que já concluíram o trabalho',
    'SESSION / MULTI-AGENT WORKFLOW': 'SESSÃO / FLUXO MULTIAGENTE',
    'Real profiles, lifecycle, and durable completion': 'Perfis reais, ciclo de vida e conclusão durável',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'Housekeeping do ThreadCells mostrando saúde do disco, backups protegidos, agendamento e política de limpeza',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / CUIDADOS COM O SERVIDOR',
    'Plan, revalidate, protect active work': 'Planejar, revalidar e proteger o trabalho ativo',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': 'Configurações de notificações do Telegram no ThreadCells com os campos de destino e credenciais claramente ocultos',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / ATENÇÃO DO PROPRIETÁRIO',
    'One low-noise installation-global route': 'Um canal global de baixo ruído para toda a instalação',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': 'SISTEMA ATIVO · CAMPOS SENSÍVEIS OCULTOS',
    'project authority resolved': 'autoridade do projeto resolvida',
    'provider capacity admitted': 'capacidade do provedor admitida',
    'session cao-atlas-control started': 'sessão cao-atlas-control iniciada',
    'resident': 'residente',
    'provider': 'provedor',
    'work context': 'contexto de trabalho',
    'heavy': 'execução pesada',
    'NATIVE BY DESIGN': 'NATIVO POR PROJETO',
    'Keep the coding agent.': 'Mantenha seu agente de programação.',
    'Add the operating system around it.': 'Acrescente o sistema operacional ao redor dele.',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'O ThreadCells controla as CLIs nativas dos provedores em terminais tmux reais. Os adaptadores informam o que o host instalado realmente suporta; recursos incompatíveis permanecem visíveis como tais, em vez de serem simulados.',
    'Codex reference adapter and first-class Claude Code adapter': 'Adaptador de referência para Codex e adaptador de primeira classe para Claude Code',
    'Provider-native authentication remains with the operator': 'A autenticação nativa do provedor permanece sob controle do operador',
    'Profiles and provider configuration are versioned control-plane artifacts': 'Perfis e configurações de provedor são artefatos versionados do plano de controle',
    'MACHINE OWNERSHIP': 'PROPRIEDADE DA MÁQUINA',
    'Your host.': 'Seu host.',
    'Your terminals.': 'Seus terminais.',
    'Your control.': 'Seu controle.',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'O ThreadCells é auto-hospedado e prioriza loopback. Ele coordena ferramentas locais poderosas, mas não apresenta um worktree como isolamento de segurança nem promete multilocação entre usuários que não confiam uns nos outros.',
    'Loopback first': 'Loopback primeiro',
    'SSH-tunnel access is the supported preview boundary.': 'O túnel SSH é o limite de acesso compatível durante a prévia.',
    'Real terminals': 'Terminais reais',
    'Inspectable tmux sessions, not hidden disposable jobs.': 'Sessões tmux que você pode inspecionar, não tarefas ocultas e descartáveis.',
    'OPEN SOURCE': 'CÓDIGO ABERTO',
    'Inspect the control plane you trust with the machine.': 'Inspecione o plano de controle ao qual você confia sua máquina.',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'O ThreadCells está disponível sob a Apache License 2.0, com a atribuição ao projeto de origem preservada nos materiais jurídicos e de procedência adequados.',
    'Stop guessing what the agents are doing.': 'Pare de adivinhar o que os agentes estão fazendo.',
    'Run the work. See the machine. Keep the result.': 'Execute o trabalho. Observe a máquina. Preserve o resultado.',
    'Open Quick Setup': 'Abrir o Quick Setup',
  },
  signals: ['FLUXOS COORDENADOS', 'HOUSEKEEPING PROTEGIDO', 'HISTÓRICO DURÁVEL', 'LOOPBACK PRIMEIRO'],
  capabilities: [
    { title: 'Estado operacional real', copy: 'Veja o que está residente, em execução, aguardando, encerrando, bloqueado ou realmente concluído, sem deduzir o estado por uma aba de terminal.' },
    { title: 'Autoridade do worktree', copy: 'Vincule o trabalho a projetos confiáveis e Git worktrees gerenciados. As permissões de escrita deixam explícitas as alterações concorrentes.' },
    { title: 'Resultados duráveis', copy: 'O trabalho delegado retorna um resultado persistido que pode ser entregue, confirmado, aceito e retirado sem perder o histórico.' },
    { title: 'Um ambiente saudável para agentes', copy: 'O ThreadCells monitora a pressão do host e limpa com segurança runtimes, logs, caches, builds e lançamentos elegíveis, protegendo o trabalho ativo e o histórico durável.' },
  ],
  steps: [
    { title: 'Crie uma sessão', copy: 'Escolha um projeto local confiável e um perfil de agente ou supervisor.' },
    { title: 'Passe o trabalho', copy: 'Um supervisor pode delegar unidades coerentes a executores e revisores de CLI nativos.' },
    { title: 'Observe o sistema', copy: 'O ThreadCells mantém o fluxo avançando entre turnos do modelo enquanto sessões, worktrees, capacidade e pressão do host continuam visíveis.' },
    { title: 'Intervenha quando solicitado', copy: 'Os resultados são preservados. As decisões do proprietário pausam o fluxo apenas quando ele realmente precisa de você.' },
  ],
  jsonLdFeatures: [
    'Sessões persistentes de agentes de CLI nativos',
    'Git worktrees gerenciados e autoridade de escrita',
    'Resultados delegados duráveis',
    'Ciclo de vida explícito dos fluxos e decisões do proprietário',
    'Controles independentes de capacidade de execução',
    'Housekeeping ciente do conjunto protegido e retirada de runtimes encerrados',
    'Notificações globais opcionais do Telegram para o ciclo de vida da instalação',
  ],
}
