import type { LandingLocaleData } from './types'

export const ptBRLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': 'AUTO-HOSPEDADO',
    'CODING-AGENT OPERATIONS': 'OPERAÇÕES DE AGENTES DE PROGRAMAÇÃO',
    'Work with AI agents ': 'Trabalhe com agentes de IA ',
    'as a system': 'como um sistema',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'O ThreadCells coordena agentes de CLI nativos, mantém fluxos abertos avançando entre turnos do modelo e cuida do ambiente de orquestração que os sustenta, no seu próprio host Linux.',
    'View on GitHub': 'Ver no GitHub',
    'Read the docs': 'Ler a documentação',
    'Start the work. Watch the system. Step in only when it needs you.': 'Inicie o trabalho. Observe o sistema. Intervenha apenas quando ele precisar de você.',
    'CONTROL / RESULT': 'CONTROLE / RESULTADO',
    'ThreadCells operating principles': 'Princípios operacionais do ThreadCells',
    'THE HARD PART': 'A PARTE DIFÍCIL',
    'Starting more agents is easy.': 'Iniciar mais agentes é fácil.',
    'Knowing what is true is not.': 'Saber o que realmente acontece não é.',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': 'Qual processo controla o worktree? Qual sessão está apenas ociosa e qual terminou? A máquina ficou sem capacidade do provedor, contextos de trabalho ou execução pesada? O revisor devolveu um resultado ou apenas parou de exibir saída?',
    'Operational questions ThreadCells answers': 'Perguntas operacionais que o ThreadCells responde',
    'SUPERVISOR': 'SUPERVISOR',
    'RUNNING': 'EM EXECUÇÃO',
    'provider 01 / 03': 'provedor 01 / 03',
    'WORKER': 'EXECUTOR',
    'COMPLETE': 'CONCLUÍDO',
    'result persisted': 'resultado persistido',
    'REVIEWER': 'REVISOR',
    'READY': 'PRONTO',
    'context 02 / 02': 'contexto 02 / 02',
    'OWNER GATE': 'DECISÃO DO PROPRIETÁRIO',
    'AUTHORITY': 'AUTORIDADE',
    'GATED': 'AGUARDANDO',
    'decision required': 'decisão necessária',
    'THE CONTROL PLANE': 'O PLANO DE CONTROLE',
    'One place to see the work,': 'Um só lugar para ver o trabalho,',
    'the host, and the handoff.': 'o host e a entrega.',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'O ThreadCells reúne a execução nativa dos agentes em uma superfície operacional: sessões, projetos, terminais, perfis, capacidade, fluxos, documentação, alertas globais opcionais do Telegram e a identidade da compilação atual.',
    'ThreadCells Home showing 30 real sessions, 218 agents, aggregate lifecycle counts, and dense session status summaries': 'Início do ThreadCells mostrando 30 sessões reais, 218 agentes, contagens agregadas do ciclo de vida e resumos detalhados do estado das sessões',
    'HOME / EXECUTION OVERVIEW': 'INÍCIO / VISÃO GERAL DA EXECUÇÃO',
    'Real release system · sensitive material excluded': 'Sistema de lançamento real · conteúdo sensível excluído',
    'LIVE RELEASE SYSTEM': 'SISTEMA DE LANÇAMENTO ATIVO',
    'LIVE RELEASE SYSTEM · IDENTITIES ANONYMIZED': 'SISTEMA DE LANÇAMENTO ATIVO · IDENTIDADES ANONIMIZADAS',
    'Session truth': 'Estado real da sessão',
    'Provider, profile, lifecycle, project, and active work remain visible.': 'Provedor, perfil, ciclo de vida, projeto e trabalho ativo continuam visíveis.',
    'Operational scale': 'Operação em escala',
    'First, Last, and Total summaries keep large durable histories readable.': 'Os resumos Primeiro, Último e Total mantêm legíveis os históricos duráveis de grande porte.',
    'CORE IDEAS': 'IDEIAS PRINCIPAIS',
    'A control room built around': 'Uma sala de controle projetada para',
    'the failure modes that matter.': 'as falhas que importam.',
    'WORKFLOW': 'FLUXO DE TRABALHO',
    'Intent goes out.': 'A intenção sai.',
    'Evidence comes back.': 'A evidência volta.',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': 'O agente de programação continua nativo. O ThreadCells deixa explícito todo o ciclo de vida ao redor dele.',
    'LIVE RELEASE TOUR': 'TOUR DO SISTEMA REAL',
    'See the control plane in motion.': 'Veja o plano de controle em funcionamento.',
    'A tour of the real release system: Home, multi-agent work, Agents, provider-reported Statistics, Housekeeping, capacity, and redacted notification settings. Operational values and lifecycle states are real; Session and Project labels are anonymized.': 'Um tour pelo sistema de lançamento real: Início, trabalho multiagente, Agents, estatísticas informadas pelo provedor, Housekeeping, capacidade e configurações de notificação ocultadas. Os valores operacionais e estados de ciclo de vida são reais; os nomes de Session e Project estão anonimizados.',
    'THREADCELLS / LIVE DATA · IDENTITIES ANONYMIZED': 'THREADCELLS / DADOS REAIS · IDENTIDADES ANONIMIZADAS',
    'Live ThreadCells release-system tour': 'Tour pelo sistema de lançamento ativo do ThreadCells',
    'The demo video is unavailable in this browser.': 'O vídeo de demonstração não está disponível neste navegador.',
    'PRODUCT EXPERIENCE': 'EXPERIÊNCIA DO PRODUTO',
    'The workflow and the host,': 'O fluxo e o host,',
    'in one operating view.': 'em uma única visão operacional.',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': 'Abra a sessão real por trás do resumo, mantenha o runtime saudável e encaminhe ao proprietário apenas as decisões importantes, sem perder o contexto durável.',
    'Expanded live ThreadCells session with processing and recovery-replaced agents': 'Sessão ativa expandida do ThreadCells com um agente em processamento e outro substituído durante a recuperação',
    'SESSION / MULTI-AGENT WORKFLOW': 'SESSÃO / FLUXO MULTIAGENTE',
    'Real lifecycle state and durable recovery evidence': 'Estados reais do ciclo de vida e evidências duráveis de recuperação',
    'ThreadCells Agents showing mixed lifecycle states and a stable action row': 'Agents do ThreadCells com diferentes estados de ciclo de vida e uma fileira estável de ações',
    'AGENTS / LIFECYCLE CONTROL': 'AGENTES / CONTROLE DO CICLO DE VIDA',
    'Status, profile, workflow, and actions stay aligned': 'Status, perfil, workflow e ações permanecem alinhados',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'Housekeeping do ThreadCells mostrando saúde do disco, backups protegidos, agendamento e política de limpeza',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / CUIDADOS COM O SERVIDOR',
    'Plan, revalidate, protect active work': 'Planejar, revalidar e proteger o trabalho ativo',
    'ThreadCells Orchestration Capacity showing independent execution limits and host pressure': 'Capacidade de orquestração do ThreadCells com limites de execução independentes e pressão do host',
    'CAPACITY / HOST ADMISSION': 'CAPACIDADE / ADMISSÃO DO HOST',
    'Resident, provider, work, and heavy limits stay independent': 'Os limites de residentes, provedores, trabalho e execução pesada permanecem independentes',
    'ThreadCells Statistics showing provider-reported token usage by session and profile': 'Estatísticas do ThreadCells com uso de tokens informado pelo provedor, por sessão e perfil',
    'STATISTICS / PROVIDER TELEMETRY': 'ESTATÍSTICAS / TELEMETRIA DO PROVEDOR',
    'Reported values stay separate from unknown data': 'Os valores informados permanecem separados dos dados desconhecidos',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': 'Configurações de notificações do Telegram no ThreadCells com os campos de destino e credenciais claramente ocultos',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / ATENÇÃO DO PROPRIETÁRIO',
    'One low-noise installation-global route': 'Um canal global de baixo ruído para toda a instalação',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': 'SISTEMA ATIVO · CAMPOS SENSÍVEIS OCULTOS',
    'project authority resolved': 'autoridade do projeto resolvida',
    'provider capacity admitted': 'capacidade do provedor admitida',
    'session cao-atlas-control started': 'sessão cao-atlas-control iniciada',
    'resident': 'residente',
    'provider': 'provedor',
    'work context': 'contexto de trabalho',
    'heavy': 'execução pesada',
    'NATIVE BY DESIGN': 'NATIVO POR PROJETO',
    'Keep the coding agent.': 'Mantenha seu agente de programação.',
    'Add the operating system around it.': 'Acrescente o sistema operacional ao redor dele.',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'O ThreadCells controla as CLIs nativas dos provedores em terminais tmux reais. Os adaptadores informam o que o host instalado realmente suporta; recursos incompatíveis permanecem visíveis como tais, em vez de serem simulados.',
    'Codex reference adapter and first-class Claude Code adapter': 'Adaptador de referência para Codex e adaptador de primeira classe para Claude Code',
    'Provider-native authentication remains with the operator': 'A autenticação nativa do provedor permanece sob controle do operador',
    'Profiles and provider configuration are versioned control-plane artifacts': 'Perfis e configurações de provedor são artefatos versionados do plano de controle',
    'TECHNICAL PREVIEW': 'PRÉVIA TÉCNICA',
    'A practical first run.': 'Um primeiro uso prático.',
    'Honest alpha boundaries.': 'Limites honestos da versão alfa.',
    'ThreadCells is for individual developers and trusted small teams that operate several coding agents on one Linux host and want durable workflow state instead of a pile of terminal tabs.': 'ThreadCells é para desenvolvedores individuais e pequenas equipes de confiança que operam vários agentes de código em um único host Linux e querem um estado de workflow durável em vez de uma pilha de abas de terminal.',
    'Start on a trusted Linux host': 'Comece em um host Linux confiável',
    'The supported baseline is Ubuntu or Debian with Python 3, Git, tmux, Node.js/npm for the Web build, and at least one provider CLI you have authenticated.': 'A base compatível é Ubuntu ou Debian com Python 3, Git, tmux, Node.js/npm para compilar a interface Web e pelo menos uma CLI de provedor na qual você tenha se autenticado.',
    'Open the installation guide': 'Abrir o guia de instalação',
    'Provider support stays explicit': 'O suporte a provedores permanece explícito',
    'Eight built-in adapters normalize launch and lifecycle. Codex is the release-acceptance reference; readiness, resume, usage, and model controls still depend on the installed provider CLI.': 'Oito adaptadores integrados normalizam a inicialização e o ciclo de vida. Codex é a referência para aceitação de releases; prontidão, retomada, uso e controles de modelo ainda dependem da CLI de provedor instalada.',
    'Check provider compatibility': 'Verificar compatibilidade de provedores',
    'Know where trust stops': 'Saiba onde a confiança termina',
    'This alpha targets one trusted operator and one host. It is loopback-first, supports remote use through an SSH tunnel, and does not treat worktrees as security sandboxes or isolate hostile tenants.': 'Esta versão alfa foi feita para um operador confiável e um único host. Ela prioriza loopback, permite uso remoto por túnel SSH e não trata worktrees como sandboxes de segurança nem isola usuários que não confiam entre si.',
    'Read the alpha limitations': 'Ler as limitações da versão alfa',
    'MACHINE OWNERSHIP': 'PROPRIEDADE DA MÁQUINA',
    'Your host.': 'Seu host.',
    'Your terminals.': 'Seus terminais.',
    'Your control.': 'Seu controle.',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'O ThreadCells é auto-hospedado e prioriza loopback. Ele coordena ferramentas locais poderosas, mas não apresenta um worktree como isolamento de segurança nem promete multilocação entre usuários que não confiam uns nos outros.',
    'Loopback first': 'Loopback primeiro',
    'SSH-tunnel access is the supported preview boundary.': 'O túnel SSH é o limite de acesso compatível durante a prévia.',
    'Real terminals': 'Terminais reais',
    'Inspectable tmux sessions, not hidden disposable jobs.': 'Sessões tmux que você pode inspecionar, não tarefas ocultas e descartáveis.',
    'OPEN SOURCE': 'CÓDIGO ABERTO',
    'Inspect the control plane you trust with the machine.': 'Inspecione o plano de controle ao qual você confia sua máquina.',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'O ThreadCells está disponível sob a Apache License 2.0, com a atribuição ao projeto de origem preservada nos materiais jurídicos e de procedência adequados.',
    'Stop guessing what the agents are doing.': 'Pare de adivinhar o que os agentes estão fazendo.',
    'Run the work. See the machine. Keep the result.': 'Execute o trabalho. Observe a máquina. Preserve o resultado.',
    'Open Quick Setup': 'Abrir o Quick Setup',
  },
  signals: ['FLUXOS COORDENADOS', 'HOUSEKEEPING PROTEGIDO', 'HISTÓRICO DURÁVEL', 'LOOPBACK PRIMEIRO'],
  capabilities: [
    { title: 'Estado operacional real', copy: 'Veja o que está residente, em execução, aguardando, encerrando, bloqueado ou realmente concluído, sem deduzir o estado por uma aba de terminal.' },
    { title: 'Autoridade do worktree', copy: 'Vincule o trabalho a projetos confiáveis e Git worktrees gerenciados. As permissões de escrita deixam explícitas as alterações concorrentes.' },
    { title: 'Resultados duráveis', copy: 'O trabalho delegado retorna um resultado persistido que pode ser entregue, confirmado, aceito e retirado sem perder o histórico.' },
    { title: 'Um ambiente saudável para agentes', copy: 'O ThreadCells monitora a pressão do host e limpa com segurança runtimes, logs, caches, builds e lançamentos elegíveis, protegendo o trabalho ativo e o histórico durável.' },
  ],
  steps: [
    { title: 'Crie uma sessão', copy: 'Escolha um projeto local confiável e um perfil de agente ou supervisor.' },
    { title: 'Passe o trabalho', copy: 'Um supervisor pode delegar unidades coerentes a executores e revisores de CLI nativos.' },
    { title: 'Observe o sistema', copy: 'O ThreadCells mantém o fluxo avançando entre turnos do modelo enquanto sessões, worktrees, capacidade e pressão do host continuam visíveis.' },
    { title: 'Intervenha quando solicitado', copy: 'Os resultados são preservados. As decisões do proprietário pausam o fluxo apenas quando ele realmente precisa de você.' },
  ],
  jsonLdFeatures: [
    'Sessões persistentes de agentes de CLI nativos',
    'Git worktrees gerenciados e autoridade de escrita',
    'Resultados delegados duráveis',
    'Ciclo de vida explícito dos fluxos e decisões do proprietário',
    'Controles independentes de capacidade de execução',
    'Housekeeping ciente do conjunto protegido e retirada de runtimes encerrados',
    'Notificações globais opcionais do Telegram para o ciclo de vida da instalação',
  ],
}
