import type { LandingLocaleData } from './types'

export const zhCNLanding: LandingLocaleData = {
  strings: {
    'SELF-HOSTED': '自托管',
    'CODING-AGENT OPERATIONS': '编码智能体运维',
    'Work with AI agents ': '让 AI 智能体',
    'as a system': '作为系统协同工作',
    'ThreadCells coordinates native CLI agents, keeps open workflows moving across model turns, and maintains the orchestration environment underneath them—on your own Linux host.': 'ThreadCells 在您自己的 Linux 主机上协调原生 CLI 智能体，让开放工作流跨模型轮次持续推进，并维护底层编排环境。',
    'View on GitHub': '在 GitHub 上查看',
    'Read the docs': '阅读文档',
    'Start the work. Watch the system. Step in only when it needs you.': '启动工作，观察系统，仅在需要您时介入。',
    'CONTROL / RESULT': '控制 / 结果',
    'ThreadCells operating principles': 'ThreadCells 运维原则',
    'THE HARD PART': '真正的难点',
    'Starting more agents is easy.': '启动更多智能体很容易。',
    'Knowing what is true is not.': '弄清真实状态却不容易。',
    'Which process owns the worktree? Which session is only idle—and which one is finished? Is the machine out of provider capacity, work contexts, or heavy execution? Did the reviewer return a result, or just stop printing?': '哪个进程拥有 worktree？哪个会话只是空闲，哪个已经结束？机器耗尽的是提供商容量、工作上下文还是重型执行容量？审阅者已经返回结果，还是只是不再输出？',
    'Operational questions ThreadCells answers': 'ThreadCells 回答的运维问题',
    'SUPERVISOR': '监督者',
    'RUNNING': '运行中',
    'provider 01 / 03': '提供商 01 / 03',
    'WORKER': '执行者',
    'COMPLETE': '已完成',
    'result persisted': '结果已持久化',
    'REVIEWER': '审阅者',
    'READY': '就绪',
    'context 02 / 02': '上下文 02 / 02',
    'OWNER GATE': '所有者关卡',
    'AUTHORITY': '权限',
    'GATED': '等待决策',
    'decision required': '需要决策',
    'THE CONTROL PLANE': '控制平面',
    'One place to see the work,': '在一个界面中查看工作、',
    'the host, and the handoff.': '主机与交接。',
    'ThreadCells wraps native agent execution in an operational surface: sessions, projects, terminals, profiles, capacity, workflows, documentation, optional global Telegram lifecycle alerts, and current build identity.': 'ThreadCells 为原生智能体执行提供统一运维界面：会话、项目、终端、配置文件、容量、工作流、文档、可选的全局 Telegram 生命周期通知，以及当前构建标识。',
    'ThreadCells Home showing 21 real sessions, 166 agents, aggregate lifecycle counts, and dense session status summaries': 'ThreadCells 首页显示 21 个真实会话、166 个智能体、生命周期汇总计数和紧凑的会话状态摘要',
    'HOME / EXECUTION OVERVIEW': '首页 / 执行概览',
    'Real release system · sensitive material excluded': '真实发布系统 · 已排除敏感内容',
    'LIVE RELEASE SYSTEM': '实时发布系统',
    'LIVE RELEASE SYSTEM · IDENTITIES ANONYMIZED': '实时发布系统 · 身份已匿名化',
    'Session truth': '会话真实状态',
    'Provider, profile, lifecycle, project, and active work remain visible.': '提供商、配置文件、生命周期、项目和活动工作始终可见。',
    'Operational scale': '规模化运维',
    'First, Last, and Total summaries keep large durable histories readable.': '首次、最近和总计摘要让庞大的持久历史仍然易读。',
    'CORE IDEAS': '核心理念',
    'A control room built around': '围绕关键故障模式',
    'the failure modes that matter.': '构建的控制室。',
    'WORKFLOW': '工作流',
    'Intent goes out.': '意图发出。',
    'Evidence comes back.': '证据返回。',
    'The coding agent stays native. ThreadCells makes the surrounding lifecycle explicit.': '编码智能体保持原生；ThreadCells 将其周围的生命周期变得明确。',
    'LIVE RELEASE TOUR': '实时发布导览',
    'See the control plane in motion.': '观看控制平面的实际运行。',
    'A tour of the real release system: Home, multi-agent work, Agents, provider-reported Statistics, Housekeeping, capacity, and redacted notification settings. Operational values and lifecycle states are real; Session and Project labels are anonymized.': '浏览真实发布系统：主页、多智能体工作、Agents、提供商报告的统计数据、Housekeeping、容量和已脱敏的通知设置。运维数值和生命周期状态均为真实数据；Session 与 Project 名称已匿名化。',
    'THREADCELLS / LIVE DATA · IDENTITIES ANONYMIZED': 'THREADCELLS / 真实数据 · 身份已匿名化',
    'Live ThreadCells release-system tour': 'ThreadCells 实时发布系统导览',
    'The demo video is unavailable in this browser.': '此浏览器无法播放演示视频。',
    'PRODUCT EXPERIENCE': '产品体验',
    'The workflow and the host,': '工作流与主机，',
    'in one operating view.': '尽在同一个运维视图。',
    'Open the real session behind the summary, keep the runtime healthy, and route high-signal owner attention without losing durable context.': '打开摘要背后的真实会话，保持运行时健康，并将高价值事项交给所有者处理，同时保留持久上下文。',
    'Expanded live ThreadCells session with processing and recovery-replaced agents': '展开的实时 ThreadCells 会话，显示正在处理的智能体和恢复时被替换的智能体',
    'SESSION / MULTI-AGENT WORKFLOW': '会话 / 多智能体工作流',
    'Real lifecycle state and durable recovery evidence': '真实生命周期状态和持久恢复证据',
    'ThreadCells Agents showing mixed lifecycle states and a stable action row': 'ThreadCells 智能体页面显示多种生命周期状态和稳定的操作栏',
    'AGENTS / LIFECYCLE CONTROL': '智能体 / 生命周期控制',
    'Status, profile, workflow, and actions stay aligned': '状态、配置文件、工作流和操作始终对齐',
    'ThreadCells Housekeeping showing disk health, protected backups, schedule, and cleanup policy': 'ThreadCells Housekeeping 显示磁盘健康、受保护备份、计划和清理策略',
    'HOUSEKEEPING / SERVER CARE': 'HOUSEKEEPING / 服务器维护',
    'Plan, revalidate, protect active work': '先规划、再验证，并保护活动工作',
    'ThreadCells Orchestration Capacity showing independent execution limits and host pressure': 'ThreadCells 编排容量显示独立的执行限制和主机压力',
    'CAPACITY / HOST ADMISSION': '容量 / 主机准入',
    'Resident, provider, work, and heavy limits stay independent': '常驻、提供商、工作和重型执行限制彼此独立',
    'ThreadCells Statistics showing provider-reported token usage by session and profile': 'ThreadCells 统计页面按会话和配置文件显示提供商报告的令牌用量',
    'STATISTICS / PROVIDER TELEMETRY': '统计 / 提供商遥测',
    'Reported values stay separate from unknown data': '已报告的值与未知数据分开显示',
    'ThreadCells Telegram notification settings with destination and credential fields visibly redacted': 'ThreadCells Telegram 通知设置，其中目标和凭据字段已明显遮盖',
    'TELEGRAM / OWNER ATTENTION': 'TELEGRAM / 所有者关注',
    'One low-noise installation-global route': '一个低噪声的安装级全局通知通道',
    'LIVE SYSTEM · SENSITIVE FIELDS REDACTED': '实时系统 · 敏感字段已遮盖',
    'project authority resolved': '项目权限已解析',
    'provider capacity admitted': '提供商容量已准入',
    'session cao-atlas-control started': '会话 cao-atlas-control 已启动',
    'resident': '常驻',
    'provider': '提供商',
    'work context': '工作上下文',
    'heavy': '重型执行',
    'NATIVE BY DESIGN': '原生设计',
    'Keep the coding agent.': '保留您熟悉的编码智能体。',
    'Add the operating system around it.': '为它补上运维系统。',
    'ThreadCells drives native provider CLIs in real tmux terminals. Provider adapters report what the installed host genuinely supports; unsupported capabilities stay visible instead of being simulated.': 'ThreadCells 在真实 tmux 终端中驱动提供商的原生 CLI。提供商适配器如实报告当前主机支持的能力；不支持的能力会明确显示，而不会被模拟。',
    'Codex reference adapter and first-class Claude Code adapter': 'Codex 参考适配器与一等支持的 Claude Code 适配器',
    'Provider-native authentication remains with the operator': '提供商原生身份验证仍由操作员掌控',
    'Profiles and provider configuration are versioned control-plane artifacts': '配置文件和提供商配置是有版本记录的控制平面制品',
    'TECHNICAL PREVIEW': '技术预览版',
    'A practical first run.': '从实用的首次运行开始。',
    'Honest alpha boundaries.': '如实说明 alpha 版边界。',
    'ThreadCells is for individual developers and trusted small teams that operate several coding agents on one Linux host and want durable workflow state instead of a pile of terminal tabs.': 'ThreadCells 面向个人开发者和相互信任的小型团队：在一台 Linux 主机上运行多个编程智能体，并用持久的工作流状态取代堆叠的终端标签页。',
    'Start on a trusted Linux host': '从可信的 Linux 主机开始',
    'The supported baseline is Ubuntu or Debian with Python 3, Git, tmux, Node.js/npm for the Web build, and at least one provider CLI you have authenticated.': '支持的基础环境是 Ubuntu 或 Debian，需要 Python 3、Git、tmux、用于构建 Web 界面的 Node.js/npm，以及至少一个已完成身份验证的提供商 CLI。',
    'Open the installation guide': '打开安装指南',
    'Provider support stays explicit': '明确呈现提供商支持情况',
    'Eight built-in adapters normalize launch and lifecycle. Codex is the release-acceptance reference; readiness, resume, usage, and model controls still depend on the installed provider CLI.': '八个内置适配器统一启动与生命周期。Codex 是发布验收的参考实现；就绪、恢复、用量和模型控制仍取决于已安装的提供商 CLI。',
    'Check provider compatibility': '查看提供商兼容性',
    'Know where trust stops': '了解信任边界',
    'This alpha targets one trusted operator and one host. It is loopback-first, supports remote use through an SSH tunnel, and does not treat worktrees as security sandboxes or isolate hostile tenants.': '此 alpha 版面向一名可信操作员和一台主机。它优先绑定 loopback，支持通过 SSH 隧道远程使用，但不会把 worktree 当作安全沙箱，也不隔离相互不信任的租户。',
    'Read the alpha limitations': '阅读 alpha 版限制',
    'MACHINE OWNERSHIP': '机器所有权',
    'Your host.': '您的主机。',
    'Your terminals.': '您的终端。',
    'Your control.': '由您掌控。',
    'ThreadCells is self-hosted and loopback-first. It coordinates powerful local tools; it does not pretend a worktree is a security sandbox or promise hostile multi-tenancy.': 'ThreadCells 采用自托管并优先绑定 loopback。它协调功能强大的本地工具，但不会把 worktree 冒充安全沙箱，也不承诺支持相互不信任的多租户环境。',
    'Loopback first': '优先使用 loopback',
    'SSH-tunnel access is the supported preview boundary.': 'SSH 隧道访问是当前预览版支持的边界。',
    'Real terminals': '真实终端',
    'Inspectable tmux sessions, not hidden disposable jobs.': '可检查的 tmux 会话，而不是隐藏的一次性作业。',
    'OPEN SOURCE': '开源',
    'Inspect the control plane you trust with the machine.': '检查您要托付机器的控制平面。',
    'ThreadCells is available under Apache License 2.0, with upstream attribution preserved in the appropriate legal and provenance materials.': 'ThreadCells 采用 Apache License 2.0 发布，并在相应的法律与来源材料中保留上游署名。',
    'Stop guessing what the agents are doing.': '不再猜测智能体正在做什么。',
    'Run the work. See the machine. Keep the result.': '运行工作，掌握机器状态，保留结果。',
    'Open Quick Setup': '打开 Quick Setup',
  },
  signals: ['协同工作流', '受保护的 HOUSEKEEPING', '持久历史', '优先使用 LOOPBACK'],
  capabilities: [
    { title: '运维真实状态', copy: '直接查看哪些进程常驻、执行、等待、排空、阻塞或真正完成，无需根据终端标签页猜测。' },
    { title: 'Worktree 权限', copy: '将工作锚定到可信项目和受管 Git worktree。写入租约让并发修改权限保持明确。' },
    { title: '持久结果', copy: '委派工作返回持久化结果，可在不丢失历史的情况下交付、确认、接受并退出活动环境。' },
    { title: '健康的智能体环境', copy: 'ThreadCells 监控主机压力，安全清理符合条件的运行时、日志、缓存、构建和发布残留，同时保护活动工作与持久历史。' },
  ],
  steps: [
    { title: '创建会话', copy: '选择可信本地项目以及智能体或监督者配置文件。' },
    { title: '交付任务', copy: '监督者可以把连贯工作委派给原生 CLI 执行者和审阅者。' },
    { title: '观察系统', copy: 'ThreadCells 让工作流跨模型轮次持续推进，同时保持会话、worktree、容量和主机压力可见。' },
    { title: '按需介入', copy: '结果会被持久保存；只有真正需要您决定时，所有者关卡才会暂停工作流。' },
  ],
  jsonLdFeatures: [
    '持久的原生 CLI 智能体会话',
    '受管 Git worktree 与写入权限',
    '持久化委派结果',
    '明确的工作流生命周期与所有者关卡',
    '相互独立的执行容量控制',
    '感知受保护集合的 Housekeeping 与关闭运行时退役',
    '可选的安装级全局 Telegram 生命周期通知',
  ],
}
